---
title: "\\vskip 1.5cm \\bfseries Explicit Weight Bias Concerns in the Fitness Industry: A Quantitative Analysis"

# If blank, the running header is the title in upper case.
shorttitle: Template for the apaquarto Extension
# Set names and affiliations.
# It is nice to specify everyone's orcid, if possible.
# There can be only one corresponding author, but declaring one is optional.
author:
  - name: Kellie Walters
    corresponding: true
    orcid: 0000-0002-0892-8028
    email: kellie.walters@csulb.edu
    # url: https://example.org/
    # Roles are optional. 
    # Select from the CRediT: Contributor Roles Taxonomy https://credit.niso.org/
    # conceptualization, data curation, formal Analysis, funding acquisition, investigation, 
    # methodology, project administration, resources, software, supervision, validation, 
    # visualization, writing, editing
    # roles:
    #  - conceptualization
    #  - writing
    affiliations:
      - id: id1
        name: "California State University, Long Beach"
        department: Department of Kinesiology
        address: 1250 Bellflower Blvd, HHS2-221
        city: Long Beach
        region: CA
        postal-code: 90840
  - name:  Alison Ede
    orcid: 0000-0001-8144-0013
    # roles:
    #  - project administration
    #  - formal analysis
    affiliations: 
      - ref: id1
author-note:
  status-changes: 
    # Example: [Author name] is now at [affiliation].
    affiliation-change: ~
    # Example: [Author name] is deceased.
    deceased: ~
  # Disclosures condensed to one paragraph, but you can start a field with two line breaks to break them up: \n\nNew Paragraph
  disclosures:
    # Example: This study was registered at X (Identifier Y).
    study-registration: ~
    # Acknowledge and cite data/materials to be shared.
    data-sharing: ~
    # Example: This article is based on data published in [Reference].
    # Example: This article is based on the dissertation completed by [citation].  
    related-report: ~
    # Example: [Author name] has been a paid consultant for Corporation X, which funded this study.
    conflict-of-interest: ~
    # Example: This study was supported by Grant [Grant Number] from [Funding Source].
    financial-support: ~
    # Example: The authors are grateful to [Person] for [Reason].
    gratitude: ~
    # Example. Because the authors are equal contributors, order of authorship was determined by a fair coin toss.
    authorship-agreements: ~
abstract: "Limited and conflicting research is available regarding weight biases in the fitness industry, yet implications of such biases are pervasive. Individuals in larger bodies often experience stigma and prejudices due to their weight, and anti-fat attitudes have been normalized in the fitness industry and associated educational pipelines. Current literature on weight biases in the fitness industry lacks context and fails to examine these biases from an intersectional lens. Therefore, this study explored how social identities (e.g., age, gender, race, etc.) influence weight biases in fitness professionals. Fitness professionals completed an electronic survey that included demographic questions and measures of weight bias (Anti-Fat Attitudes Test; AFAT) and body dissatisfaction (Contour Drawing Rating Scale). Women in the healthy (2.02 ± .51) and overweight (1.97 ± .49) BMI categories had significantly greater total AFAT scores (p = .003 and p = .023, respectively) compared to women in the obese BMI category (1.63 ± .48). For participants who had completed some college, those who were classified in the healthy BMI category had significantly greater total AFAT scores (2.05 ± .50) compared to those in the overweight BMI category (1.72 ± .46). For participants who completed a master’s degree, those in the healthy BMI category (2.08 ± .56) and overweight BMI category (2.05 ± .43) had significantly greater total AFAT scores compared to those in the obese BMI category (1.48 ± .46). There was a direct effect of gender, body dissatisfaction, race and BMI on AFAT subscales. There was also a significant direct effect of body dissatisfaction on AFAT subscales. Across all variables, AFAT scores were highest for the physical subscale (2.69 ± .91) and lowest for the social subscale (1.43 ± .45). Fitness professionals exhibit explicit weight biases, and future research should examine the implications of such biases."

# Put as many keywords at you like, separated by commmas (e.g., [reliability, validity, generalizability])
keywords: [Anti-fat bias, fitness professionals, social identities, explicit bias, weight stigma]
# If true, tables and figures are mingled with the text instead of listed at the end of the document.
floatsintext: false
# Numbered lines (.pdf and .docx only)
numbered-lines: false
# File with references
bibliography: bibliography.bib
# Masks references that appear in the masked-citations list
mask: false
masked-citations:
  - schneider2012cattell
  - schneider2015intelligence
# Language options. See https://quarto.org/docs/authoring/language.html
lang: en
language:
  citation-last-author-separator: "and"
  citation-masked-author: "Masked Citation"
  citation-masked-date: "n.d."
  citation-masked-title: "Masked Title"
  title-block-author-note: "Author Note"
  title-block-correspondence-note: "Correspondence concerning this article should be addressed to"
  title-block-role-introduction: "Author roles were classified using the Contributor Role Taxonomy (CRediT; https://credit.niso.org/) as follows:"

format:
  apaquarto-docx: default
  apaquarto-html: default
  apaquarto-pdf:
    journal: "\\bfseries \\Large Journal of Kinesiology and Wellness"
    volume: "\\vskip 1mm \\normalsize A Publication of the Western Society for Kinesiology and Wellness \\newline Volume 13, Number 1, Pages 1--9, 2024\\newline ISSN# 2323-4505"
    documentmode: jou
    keep-tex: true
nocite: |
  @*
---

```{r}
#| label: setup
#| include: false
library(conflicted)
library(tidyverse)
library(flextable)
library(ftExtra)
library(officer)
library(knitr)

conflicts_prefer(dplyr::filter, .quiet = TRUE)
conflicts_prefer(flextable::separate_header, .quiet = TRUE)
```

Weight bias (i.e., anti-fat bias) is unreasonable judgments about someone based on weight @washington2011a (Washington, 2011). It is pervasive in the health industry, including those who work as physicians (Schwartz et al., 2003), physical educators (Fontana et al., 2017), fitness professionals (Dimmock et al., 2009; Fontana et al., 2018; Robertson & Vohora, 2008), and exercise science students (Chambliss et al., 2004; Fontana et al., 2013; Langdon et al., 2016; Rukavina et al., 2010; Wijayatunga et al., 2019). In the fitness industry, potential implications of these biases include negative perceptions of larger bodied individuals’ abilities, motivation, and potential job qualifications (Sartore & Cunningham, 2007). Weight stigma is defined as discriminatory acts towards individuals in larger bodies due to their size (Washington, 2011). Consequences of experiencing weight stigma include a) poor physical health, such as an increased likelihood of maintained obesity or weight gain (Sutin & Terracciano, 2013), and b) increased psychological distress, including greater rates of body dissatisfaction and symptoms of eating disorders (Vartanian & Novak, 2011). Paradoxically, individuals who experience weight stigma are more likely to avoid exercise as a result of internalized anti-fat attitudes (Vartanian & Novak, 2011) and experience an increased allostatic load (cumulative response to ongoing stress) ((Guidi et al., 2021), which has a greater impact on their health than being in a larger body does (Gordon, 2020; Milburn et al., 2019).

A systematic review on weight bias among exercise and nutrition professionals included 31 studies; however, only three focused specifically on fitness professionals (e.g., personal trainers or group fitness instructors) compared to “exercise professional trainees” (e.g., exercise science students). Robertson and Vohora (2008) were the first to report strong anti-fat implicit and explicit biases in fitness professionals (n = 57, “gym instructors” and “aerobics instructors”), with the bias being greater in those who had never been overweight and believed obesity was controllable. In a study surveying fitness center employees (management and administrative staff n = 15, personal trainers n = 16, fitness instructors n =19, and exercise/sport physiologists n = 20), Dimmock et al. (2009) reported a moderately strong implicit bias, but no explicit bias, towards individuals in larger body sizes. More recently, Fontana et al. (2018) found that personal trainers (n = 52) report strong implicit biases against individuals who are obese.

Recently, Zaroubi et al. (2021) published a review article on the predictors of weight bias in fitness professionals and exercise science students (Zaroubi et al., 2021). Most of the studies in this review sampled undergraduate students in the exercise science field, with only four of the 18 sample fitness professionals. Of those four studies, only three included weight bias as a dependent variable (Dimmock et al., 2009; Fontana et al., 2018; Robertson & Vohora, 2008). A thematic analysis was conducted, and six themes emerged. First, exercise science students and fitness professionals strongly believe that weight is controllable and associate individuals with larger bodies with negative attributes such as laziness. Second, the relationship between gender and weight bias is still unknown as data is conflicting. Third, being enrolled in an exercise science or similar educational program is likely a predictor of weight bias. Fourth, personal and psychosocial factors (e.g., the tendency to internalize an athletic body as the ideal body shape) likely influence weight bias. Fifth, knowledge of the uncontrollable aspects of obesity (e.g., genetics) is likely to lower weight bias. Lastly, there is conflicting evidence regarding the influence of one’s personal history with someone in a larger body. Chambliss et al. (2004) report that a lack of family history of having a larger body leads to higher explicit weight bias in fitness professionals and regular exercisers Field (Chambliss et al.(Chambliss et al., 2004). In contrast, DeBarr and Pettit reported no statistical differences in weight bias held by health educators classified as overweight compared to normal weight. Little research has examined explicit weight biases of fitness professionals, and no research has focused on whether their social identities and/or role in the industry (e.g., group fitness instructor versus personal trainer) influence their weight bias. This research is particularly important due to the influential nature of this field. Clients often look to fitness professionals for advice and education on changing their health behaviors. If fitness professionals hold strong weight biases, they may contribute to a harmful cycle whereby their clients become less likely to participate and/or adhere to their health behavior changes. Fitness professionals need to have more knowledge of weight biases. Thus, the study aimed to examine the influence of age, gender, body dissatisfaction, race, role in industry, BMI, income, and education on weight bias in fitness professionals.

# Methods

## Participants

The original data set included participants (n = 366) who identified as fitness professionals in various settings. Participants reported their role in the industry with the option to choose from certified personal trainer (n = 30), group fitness instructor (n = 107), facility club manager/director/owner (n = 2), physical/occupational therapist (n = 2), health/wellness coach (n = 2), strength and conditioning coach (n = 4), other with the option to enter their role (n = 15), and multiple (those who hold more than one role in the industry; n = 189). Due to low sample sizes within some of the roles (facility club manager, physical/occupational therapy, health/wellness coach, strength and conditioning coach, and others), only data from individuals who marked that they were personal trainers, group fitness instructors, or those who held multiple roles were included in the analysis (n = 326). The participants included a diverse sample, with 40.5% identifying as non-white (11% Black, 6.1% Asian, 8.6% Hispanic, 3.1% other, and 9.5% multi-race) and 59.5% identifying as White. Participants identified as female (n = 262) and male (n = 55), and their age was relatively equally distributed across all age groups ranging from 18-55+ (21.2% 18-24 years old, 26.1% 25-34 years old, 22.4% 35-44 years old, 17.2% 45-54 years old, and 12.9% 55 years old and older). Participants were well educated (66% having a minimum bachelor’s degree), and 43.7% reported an annual household income of \$100,000 or more.

Recruitment occurred via word of mouth, email, and social media. Participants were asked to complete an electronic survey about weight biases in the fitness industry. IRB approval and written participant consent were received before data collection. After four months of data collection, the authors recognized that the majority of respondents up until that point were white (84%) and subsequently amended the IRB application to include an incentive (\$20 gift card) for individuals of color to participate in the study. After adjusting the recruitment language to include information about the incentive, an additional 109 fitness professionals who identified as persons of color completed the survey.

## Instruments

In addition to demographic data (participants’ age, weight, height, BMI, gender, race, education, income, and role in the industry), the following instruments were used in this study.

### Anti-fat Attitudes Test (AFAT)

The modified 34-item AFAT scale (Lewis et al., 1997) measured explicit bias attitudes towards individuals in larger bodies (i.e., weight bias or anti-fat bias). This psychometrically sound scale (Dimmock et al., 2009; Lewis et al., 1997; Wijayatunga et al., 2019) consisted of a modified 5-point Likert scale with 1 being strongly disagree and 5 being strongly agree. To avoid social response bias, participants were reminded multiple times that their responses were anonymous. Positively worded statements were reverse coded, so higher scores represented greater anti-fat bias. The questionnaire includes three subscales: (1) social/character disparagement (e.g., “I prefer not to associate with fat people”), (2) physical/romantic unattractiveness (e.g., “Fat people are physically unattractive”), and (3) weight control/blame (e.g., “There is no excuse for being fat”), as well as a total composite score (Lewis et al., 1997). Individual questions were averaged for each subscale and the total AFAT composite score. Cronbach’s alpha was .71, .78, and .71 for the social, attraction, and blame subscales, respectively, indicating adequate internal consistency.

### Contour Drawing Rating Scale

The psychometrically sound Contour Drawing Rating Scale assessed participants’ body dissatisfaction (Gardner & Brown, 2010). As introduced by Thompson and Gray (1995), the Contour Drawing Rating Scale utilizes the drawings of masculine and feminine human figures in the front view. Nine drawings illustrate each gender, with illustrations representing progressively larger body shapes on a scale of 1 to 9. First, the participants chose which body type they most identified with (e.g., “Which bodies do you mostly identify with?”), with group A being body shapes traditionally assigned to women and group B being body shapes traditionally assigned to men (Figure 1). As noted earlier, this data assessed participants’ gender identity. The participants answered two more questions including: (1) “On a scale from 1-9, rate what your CURRENT body size based on the images above”, and (2) “On a scale from 1-9, rate what you would IDEALLY want to look like based on the images above.” Participants’ body dissatisfaction was calculated by subtracting the number associated with their ideal image from the number associated with their current image.

Positive scores indicated a desired ideal body smaller than their current perceived body size, and negative scores indicated an ideal body larger than their current perceived body size. Scores ranged from -2 to 4 and were categorized into four groups: (1) moderate dissatisfaction, desire to be larger (scores of -2 and -1), (2) no dissatisfaction (scores of 0, meaning their current body size was their ideal body size), (3) moderate dissatisfaction, desire to be smaller (scores of 1 and 2), and (4) high dissatisfaction, desire to be smaller (scores of 3 and 4). While body dissatisfaction as a construct represents a desire to be a different shape, creating groups distinguishing positive and negative scores allows for a more nuanced understanding of body dissatisfaction. A desire to be smaller should represent a greater internalization of weight bias than a desire to be larger, as a desire to have a smaller body size is consistent with the societal ideal that thinner is more valued.

## Statistical Analysis

Two-way ANOVAs were conducted to examine the effects of every possible 2-way interaction of the eight IVs (age, gender, body dissatisfaction, race, BMI, role, education, and income) on AFAT total (Tables 1-6). When no interaction effects were found, one-way ANOVAs and MANOVAs were conducted to assess the direct effect of the IVs on AFAT total and AFAT subscales, respectively. Partial eta squared (partial η²) was used to measure the effect size of variables, with 0.1, 0.06, and 0.14 indicating a small, medium, and large effect size, respectively (Fritz et al., 2012). Outliers were assessed by inspection of a boxplot, normality was assessed using Shapiro-Wilk's normality test for each cell of the design, and Levene's test assessed homogeneity of variances. All data is presented as mean ± standard deviation. SPSS Version 27 was used to analyze the data, and significance was noted by a p-value \< 0.05.

# Results

There was a statistically significant interaction between gender and BMI on total AFAT scores, $F(2,272) = 3.139, p = .045, \text{partial } \eta^2 = .023$. Therefore, an analysis of simple main effects for gender and BMI was performed with statistical significance receiving a Bonferroni adjustment. Women in the healthy $(2.02 \pm .51)$ and overweight $(1.97 \pm .49)$ BMI categories had significantly greater total AFAT scores $(p = .003 \text{ and } p = .023, \text{respectively})$ compared to women in the obese BMI category $(1.63 \pm .48)$. There was also a statically significant interaction between education and BMI on total AFAT scores, $F(9,266) = 2.201, p = .022, \text{partial } \eta^2 = .069$. An analysis of simple main effects for education and BMI was performed with statistical significance receiving a Bonferroni adjustment. For participants who had completed some college, those who were classified in the healthy BMI category had significantly greater total AFAT scores $(2.05 \pm .50)$ compared to those in the overweight BMI category $(1.72 \pm .46), p = .045$. For participants who completed a master’s degree, those in the healthy BMI category $(2.08 \pm .56)$ and overweight BMI category $(2.05 \pm .43)$ had significantly greater total AFAT scores $(p = .003 \text{ and } .016, \text{respectively})$ compared to those in the obese BMI category $(1.48 \pm .46)$. No other interaction effects were found. Therefore, one-way ANOVAs and MANOVAs were conducted to assess the direct effect of the IVs on AFAT total and AFAT subscales, respectively. The mean total AFAT scores for each IV are listed in Table 7.

## Age

A one-way ANOVA was conducted to determine if total anti-fat bias differed by age group. Homogeneity of variances was violated, as assessed by Levene’s Test of Homogeneity of Variance $(p = .001)$. Therefore, Welch’s F and Games-Howell were used to assess significance. There were no statistically significant differences in total AFAT scores between the different age groups, Welch’s F $(4, 128.682) = 0.632, p = .640$. A one-way MANOVA was run to determine if anti-fat bias subscale scores differed by age group. Across all age groups, AFAT scores were highest for the physical subscale $(2.69 \pm 0.92)$ and lowest for the social subscale $(1.43 \pm 0.45)$, with the blame subscale scores between $(2.17 \pm 0.74)$. No statistically significant differences existed between age groups for all three AFAT subscales, $F(12,852) = 1.415, p =.153; \text{Pillai’s Trace} = .059; \text{partial } \eta^2 = .020$.

| Measure                       | *F*  | *df* | *p*     | $\eta_{p}^{2}$ |
|-------------------------------|------|------|---------|----------------|
| Gender X race                 | 0.26 | 4    | 0.905   | 0.00           |
| Gender X age                  | 1.27 | 4    | 0.280   | 0.02           |
| Gender X education            | 0.08 | 4    | 0.988   | 0.00           |
| Gender X income               | 0.60 | 7    | 0.757   | 0.02           |
| Gender X BMI                  | 3.14 | 2    | 0.045\* | 0.02           |
| Gender X body dissatisfaction | 0.18 | 3    | 0.908   | 0.00           |
| Gender X industry role        | 0.53 | 2    | 0.592   | 0.00           |

: Summary of Two-way ANOVAs by Age {#tbl-tb1 apa-note="Note below table" data-quarto-disable-processing="true" tbl-colwidths="\[50,12.5,12.5,12.5,12.5\]"}

## Gender

A one-way ANOVA was conducted to determine if total anti-fat bias differed by gender. There was a statistically significant difference in total AFAT scores between genders, $F(1, 280) = 8.320, p = .004$. Participants who identified as men reported significantly greater total AFAT scores $(2.19 \pm 0.41)$ than those who identified as women $(1.96 \pm 0.51)$. A one-way MANOVA was run to determine if anti-fat bias subscales differed by gender. For both genders, AFAT scores were highest for the physical subscale $(2.71 \pm 0.92)$ and lowest for the social subscale $(1.43 \pm 0.46)$, with the blame subscale scores between $(2.17 \pm 0.74)$. The differences between genders on the AFAT physical subscale $F(1,280) = 6.940, p < .05; \text{partial } \eta^2 = .024$ and AFAT blame subscale $F(1,280) = 6.909, p < .05; \text{partial } \eta^2 = .024$ were statistically significant. Participants who identified as men reported significantly greater AFAT physical scores $(3.02 \pm .91; p<.05)$ and AFAT blame scores $(2.42 \pm .62; p<.05)$ than participants who identified as women $(2.64 \pm .91 \text{ and } 2.12 \pm .75, \text{respectively})$.

```{asis}
#| label: tbl-mytable2
#| tbl-cap: My Table
#| apa-twocolumn: false
#| apa-note: This is a note below the markdown table.
#| ft.align: center
#| echo: true


| Default | Left | Right | Center |
|---------|:-----|------:|:------:|
| 12      | 12   |    12 |   12   |
| 123     | 123  |   123 |  123   |
| 1       | 1    |     1 |   1    |
```

## Body Dissatisfaction

A one-way ANOVA was conducted to determine if total anti-fat bias differed by body dissatisfaction. There were statistically significant differences in total AFAT scores between different levels of body dissatisfaction, $F(3, 276) = 4.147, p < .05$. Those participants in the moderate dissatisfaction, desire to be smaller group $(1.94 \pm .50)$ had significantly lower total AFAT scores compared to those in the no dissatisfaction group $(2.15 \pm .49), p = .017$.

A one-way MANOVA was run to determine if anti-fat bias subscales differed by body dissatisfaction. AFAT scores were highest for the physical subscale $(2.71 \pm 0.92)$ and lowest for the social subscale $(1.42 \pm 0.44)$, with the blame subscale scores between $(2.17 \pm 0.74)$. The effect of body dissatisfaction on AFAT subscales was statistically significant, $F(9,828) = 2.010, p < .05; \text{Pillai’s Trace} = .064; \text{partial } \eta^2 = .021$. Tukey post-hoc tests showed that participants in the moderate dissatisfaction, desire to be smaller group $(1.36 \pm .42)$ had significantly lower AFAT social scores than participants in the no dissatisfaction group $(1.57 \pm .49), p = .004$.

## Race

A one-way ANOVA was conducted to determine if total anti-fat bias differed by race. Homogeneity of variances was violated, as assessed by Levene’s Test of Homogeneity of Variance $(p = .001)$. Therefore, Welch’s F and Games-Howell were used to assess significance. Total AFAT scores were statistically significantly different by race, Welch’s F $(5,47.989) = 7.564, p < .001$. White participants reported significantly lower total AFAT scores $(1.86 \pm .51)$ than Black $(2.14 \pm .40, p = .008)$, Asian $(2.25 \pm .34, p = .001)$, and Hispanic $(2.25 \pm .38, p <.001)$ participants. A one-way MANOVA was run to determine if anti-fat bias subscales differed by race. AFAT scores were highest for the physical subscale $(2.68 \pm 0.92)$ and lowest for the social subscale $(1.42 \pm 0.44)$, with the blame subscale scores between $(2.17 \pm 0.74)$. The effect of race on AFAT subscales was statistically significant, $F(15,834) = 7.813, p < .001; \text{Pillai’s Trace} = .370; \text{partial } \eta^2 = .123$. Tukey post-hoc tests demonstrated that participants who identified as White reported significantly lower AFAT physical scores $(2.26 \pm .72)$ than participants who identified as Black $(3.46 \pm .69, p<.001)$, Asian $(3.12 \pm .71, p<.001)$, Hispanic $(3.30 \pm .87, p<.001)$, other $(3.46 \pm .81, p<.001)$, and multi-race $(3.04 \pm 1.02, p<.001)$.

## BMI

A one-way ANOVA was conducted to determine if total anti-fat bias differed by BMI. There were statistically significant differences in total AFAT scores between different levels of BMI, $F(2, 282) = 3.278, p < .05$. Those participants in the healthy BMI category $(2.06 \pm .51)$ had significantly greater total AFAT scores compared to those in the obese BMI category $(1.79 \pm .53), p = .034$. A one-way MANOVA was run to determine if anti-fat bias subscales differed by BMI. AFAT scores were highest for the physical subscale $(2.71 \pm 0.91)$ and lowest for the social subscale $(1.44 \pm 0.45)$, with the blame subscale scores between $(2.19 \pm 0.74)$. There were significant differences in the AFAT subscale scores between BMI categories, $F(6, 560) = 2.126, p = .049; \text{Pillai’s Trace} = .044; \text{partial } \eta^2 = .022$. Tukey post-hoc tests demonstrated that participants in the healthy BMI category reported significantly greater AFAT blame scores $(2.27 \pm .70)$ than participants in the obese BMI category $(1.76 \pm .77, p = .003)$.

## Role in Industry

A one-way ANOVA was conducted to determine if total anti-fat bias differed by role in the industry. There were no statistically significant differences in total AFAT scores between roles, $F(2, 287) = 0.487, p = .615$. A one-way MANOVA was run to determine if anti-fat bias subscales differed by role in the industry. AFAT scores were highest for the physical subscale $(2.69 \pm 0.92)$ and lowest for the social subscale $(1.43 \pm 0.50)$, with the blame subscale scores between $(2.17 \pm 0.74)$. There were no significant differences in any of the AFAT subscale scores between the different industry roles, $F(6, 572) = 1.60, p = .142; \text{Pillai’s Trace} = .033; \text{partial } \eta^2 = .017$.

## Education

A one-way ANOVA was conducted to determine if total anti-fat bias differed by education level. There were no statistically significant differences in total AFAT scores between education levels, $F(6, 282) = 1.528, p = .169$. A one-way MANOVA was run to determine if anti-fat bias subscales differed by education level. AFAT scores were highest for the physical subscale $(2.69 \pm 0.92)$ and lowest for the social subscale $(1.43 \pm 0.45)$, with the blame subscale scores between $(2.17 \pm 0.74)$. There were no statistically significant differences in the AFAT subscale scores between different levels of education, $F(18,846) = 0.083, p = .158; \text{Pillai’s Trace} = .083; \text{partial } \eta^2 = .028$.

## Income

A one-way ANOVA was conducted to determine if total anti-fat bias differed by income level. Homogeneity of variances was violated, as assessed by Levene’s Test of Homogeneity of Variance $(p = .028)$. Therefore, Welch’s F and Games-Howell were used to assess significance. There were no statistically significant differences in total AFAT scores between the different income groups, Welch’s F $(7, 108.923) = 1.472, p = .185$. A one-way MANOVA was run to determine if anti-fat bias subscales differed by income level. AFAT scores were highest for the physical subscale $(2.70 \pm 0.92)$ and lowest for the social subscale $(1.43 \pm 0.45)$, with the blame subscale scores between $(2.17 \pm 0.73)$. There were no statistically significant differences in the AFAT subscale scores between different levels of income, $F(21,819) = 1.39, p = .141; \text{Pillai’s Trace} = .100; \text{partial } \eta^2 = .033$.

# Discussion

A key finding from this study is that a fitness professional's BMI interacts with their gender and education level in relation to total weight bias. Women in the healthy and overweight BMI category had significantly greater total weight bias compared to those in the obese BMI category. This supports previous findings that higher BMI is associated with lower anti-fat bias (Elran-Barak & Bar-Anan, 2018; Marini et al., 2013). These findings suggest that being in a smaller body increases women's likelihood of exhibiting greater anti-fat biases. Results from this study demonstrate that those with more education reported greater weight biases in smaller (i.e., healthy BMI category) and larger bodies (i.e., overweight BMI category) than those with less education who only reported greater weight biases in smaller bodies. Previous research has found that as physical education students advance in their degrees, they will likely demonstrate greater weight bias (O'Brien et al., 2007; Wijayatunga et al., 2019). Therefore, a relationship between education level and severity of weight biases may exist whereby, despite being in a larger body, students with more education may be more likely to hold negative beliefs about individuals in larger bodies due to internalizing the weight biases inherent in health education (Zaroubi et al., 2021).

Results from this study and others demonstrate that men reported significantly greater anti-fat biases when controlling for BMI than women (Chambliss et al., 2004; Langdon et al., 2016). From a societal perspective, it is more acceptable for men to be in larger bodies than women (Heise et al., 2019). However, when BMI was included in this study's analysis, women with smaller bodies were the ones who held greater anti-fat biases. The drive for thinness that is perpetuated in the fitness industry may contribute to women internalizing messaging about what it means to be in a larger body, which may contribute to having a greater anti-fat bias.

Both females and males in the healthy BMI category reported significantly greater total weight bias compared to those in the obese BMI category. These findings result from cultural norms where larger bodies are often viewed as less desirable than smaller bodies. This is seen in the fitness industry's lack of images of people with larger bodies and the current culture of dismissing people as less able, less self-disciplined, and lacking willpower (Foster et al., 2003; Hebl & Xu, 2001). Interestingly, fitness professionals in this study with moderate body dissatisfaction and a desire to be smaller reported significantly lower total and social weight bias than those without no dissatisfaction. Experiencing body dissatisfaction may increase empathy towards individuals in larger bodies, thereby reducing their weight bias. However, further examination is necessary to better understand this relationship. Similarly, the two levels of education associated with influencing the relationship between BMI and total AFAT scores (some college and having a Master's Degree) are separated by two additional levels of education (Associate Degree and Bachelor's Degree), which makes drawing any conclusion about the relationship between education, BMI, and anti-fat bias difficult. Thus, further research examining this relationship is warranted as well.

Regardless of age, gender, body dissatisfaction, race, role in industry, income, or education, total AFAT scores and all AFAT subscale scores were below the anti-fat bias threshold 3. Dimmock et al. (2009) reported similar results with mean explicit weight bias values of 1.65, 2.66, and 2.92 for social, physical, and blame AFAT subscales. However, conflicting research demonstrates that fitness professionals possess strong implicit anti-fat biases (Dimmock et al., 2009; Fontana et al., 2018; Robertson & Vohora, 2008). The differences in findings could result from measuring implicit versus explicit weight bias, where implicit bias measures biases that emerge subconsciously without awareness, and explicit bias measures conscious biases (Gawronski & Bodenhausen, 2006). A limitation of this study was the use of explicit rather than implicit weight bias measures, which increases the likelihood of response bias. The participants who chose to complete this study have more favorable attitudes towards individuals in larger bodies, which is why they were interested in participating. Future research should examine how social identities and industry roles influence implicit weight biases in the fitness industry.

Despite AFAT scores not being below the anti-fat bias threshold, participants still reported anti-fat beliefs, particularly for the physical and blame subscales. The blame AFAT score was consistently the greatest of all of the AFAT subscales for each of the IVs, and participants in the healthy BMI category had significantly greater AFAT blame scores compared to individuals in the obese category. While this is the first study to demonstrate such findings in fitness professionals, Chambliss et al. (2004) and Dimmock et al. (2009) reported similar, high blame subscale scores in exercise science students and fitness center employees, respectively. In most fitness certifications and curricula, there is a strong focus on preventing obesity, where there is often an oversimplification of obesity, which blames and stigmatizes individuals in larger bodies (Roehling et al., 2007; Tesh & Tesh, 1988). Interventions designed to reduce weight bias by including information about the complex nature of obesity (e.g., uncontrollable causes of obesity) have been shown to successfully reduce blame (Rukavina et al., 2010; Wijayatunga et al., 2019) and social weight bias (Rukavina et al., 2010) in undergraduate students. While future research examining the effect of similar interventions on weight biases in fitness professionals might be useful, Gibson (2021) argues that even fat activists who try to resolve individuals in larger bodies of responsibility associated with their size inadvertently support the notion of blame. By arguing that individuals in larger bodies who exercise and eat well are naturally larger and "innocent" of their body size (a term Gibson deems "good fatty"), fat activists highlight the notion that those in larger bodies who are not active or eating well ("bad fatty) are "guilty" and therefore to blame for their bodies. Thus, the cognitive response of blame in relation to one's body size is further exasperated.

An additional novel finding in this study was the difference in anti-fat bias based on one's race. In opposition to Perez-Lopez et al. (2001), who reported greater anti-fat attitudes in White individuals, White participants in this study reported significantly lower total anti-fat bias compared to Black, Asian, and Hispanic participants. Similarly, White participants reported significantly lower AFAT physical scores compared to every other race. This finding contradicts Puhl et al. (2015), who found that in a U.S. sample, Black participants scored lower on fat phobia and fat bias measures compared to White participants. In the current study, breaking down weight bias specifically into the physical subscale provides an important context for the contradictory finding. The physical subscale represents how attractive or unattractive one finds fat people. This is particularly relevant for the sample population, where social norms within the fitness industry uniquely prime individuals to have stronger weight biases by framing weight loss goals to improve attractiveness.

Societally, we are primed to view thin, white bodies as more attractive, which is rooted in a racist history (Strings, 2020). Research demonstrates that greater exposure to anti-fat culture leads to stronger anti-fat attitudes (Durso & Latner, 2008; O'Brien et al., 2007), which leads to internalizing such messages (Mensinger et al., 2016; Pearl et al., 2019) However, more recent messaging around body positivity, which aims to counter the views that only thin bodies are attractive and worthy, has been criticized as a white feminist perspective (Johansson, 2021). If bodies other than the white, thin ideal are considered to be unattractive, it is too much to challenge dominant stereotypes to accept all other deviant aspects of non-white fat bodies (e.g., race, hair, etc.); therefore, white women are the only group allowed the privilege of viewing their own larger bodies as attractive or adopt self-love (Johansson, 2021; Strings et al., 2019). This can then reinforce internalized views of unattractiveness for non-white fitness professionals, as they have not been able to receive the benefits of body positivity under white supremacy.

In addition, other aspects of the fitness industry function under white privilege. White fitness professionals are more likely to have control and ownership over fitness spaces, which can make it challenging to create spaces that counter racist attitudes (Strings, 2020; Strings et al., 2019). People of color and those in larger bodies continue to be underrepresented in the fitness industry and have likely experienced many other biases themselves, which leads to a greater potential for internalizing other biases prevalent in the industry.

Another area that needs continued exploration is the influence of one's role in the industry on weight biases. While this paper sought to understand this relationship, the small sample size within each role made it difficult to make comparisons, which limited the analysis to only comparing three roles. Additionally, most fitness professionals have many roles in the industry (e.g., personal trainer and group fitness instructor), which makes interpreting data difficult. It is also possible that the type of certification (rather than a role in the industry) influenced weight bias more.

## Conclusion

This study reveals complex relationships in anti-fat biases among fitness professionals. The interaction between BMI, gender, and education level reveals intriguing patterns, challenging conventional assumptions about weight biases within the fitness industry. Both genders in the healthy BMI category express greater weight biases, indicating societal favoritism towards smaller bodies. Despite participants scoring below the defined anti-fat bias threshold, the persistence of anti-fat beliefs, especially in the blame subscale, calls attention to underlying biases not fully captured by explicit measures. The blame directed towards individuals in larger bodies may be perpetuated by oversimplified narratives surrounding obesity prevalent in fitness certifications and curricula. The study also breaks new ground by exploring racial disparities in anti-fat biases within the fitness industry. The unexpected finding that White participants report lower anti-fat biases challenges previous research, pointing to the unique influence of the fitness industry's culture on shaping perceptions. This underscores the importance of considering industry-specific contexts in understanding weight biases.

In conclusion, this study unravels intricate dynamics of weight biases in fitness professionals, challenging assumptions and emphasizing industry-specific influences. It calls for ongoing research to comprehensively understand the multifaceted factors shaping biases in this unique professional domain. This study uses a diverse sample to advance the current literature on weight bias concerns in the fitness industry. This novel research is a necessary first step to future research (e.g., intervention studies) that explores how biases in the fitness industry influence the health behaviors of those seeking fitness guidance.

# References

<!-- References will auto-populate in the refs div below -->

::: {#refs}
:::
