<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Mackinsey Woolever">
<meta name="author" content="Ovande Furtado Jr">
<meta name="author" content="Jere D. Gallagher">
<meta name="keywords" content="Assessment, Fundamental Movement Skills, Children, Movement Competence, Rating Scales, Assessment, Reliability, Agreement, Concurrent Validity">

<title>Collecting Concurrent Validity, Expert-Rater Agreement, and Inter/Intra-Rater Reliability for the FG-COMPASS</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="woolever_files/libs/clipboard/clipboard.min.js"></script>
<script src="woolever_files/libs/quarto-html/quarto.js"></script>
<script src="woolever_files/libs/quarto-html/popper.min.js"></script>
<script src="woolever_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="woolever_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="woolever_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="woolever_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="woolever_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="woolever_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="_extensions/wjschne/apaquarto/apa.css">
</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass" id="toc-collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass" class="nav-link active" data-scroll-target="#collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass">Collecting Concurrent Validity, Expert-Rater Agreement, and Inter/Intra-Rater Reliability for the FG-COMPASS</a></li>
  <li><a href="#author-note" id="toc-author-note" class="nav-link" data-scroll-target="#author-note">Author Note</a></li>
  <li><a href="#abstract" id="toc-abstract" class="nav-link" data-scroll-target="#abstract">Abstract</a></li>
  <li><a href="#collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass-1" id="toc-collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass-1" class="nav-link" data-scroll-target="#collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass-1">Collecting Concurrent Validity, Expert-Rater Agreement, and Inter/Intra-Rater Reliability for the FG-COMPASS</a></li>
  <li><a href="#materials-and-methods" id="toc-materials-and-methods" class="nav-link" data-scroll-target="#materials-and-methods">Materials and Methods</a>
  <ul class="collapse">
  <li><a href="#participants" id="toc-participants" class="nav-link" data-scroll-target="#participants">Participants</a></li>
  <li><a href="#measures" id="toc-measures" class="nav-link" data-scroll-target="#measures">Measures</a>
  <ul class="collapse">
  <li><a href="#tgmd-2" id="toc-tgmd-2" class="nav-link" data-scroll-target="#tgmd-2">TGMD-2</a></li>
  <li><a href="#fg-compass" id="toc-fg-compass" class="nav-link" data-scroll-target="#fg-compass">FG-COMPASS</a></li>
  </ul></li>
  <li><a href="#research-assistants" id="toc-research-assistants" class="nav-link" data-scroll-target="#research-assistants">Research Assistants</a></li>
  <li><a href="#procedures" id="toc-procedures" class="nav-link" data-scroll-target="#procedures">Procedures</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection">Data collection</a></li>
  </ul></li>
  <li><a href="#data-analysis" id="toc-data-analysis" class="nav-link" data-scroll-target="#data-analysis">Data Analysis</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#concurrent-validity" id="toc-concurrent-validity" class="nav-link" data-scroll-target="#concurrent-validity">Concurrent Validity</a></li>
  <li><a href="#inter-rater-reliability" id="toc-inter-rater-reliability" class="nav-link" data-scroll-target="#inter-rater-reliability">Inter-Rater Reliability</a></li>
  <li><a href="#intra-rater-reliability-for-the-fg-compass" id="toc-intra-rater-reliability-for-the-fg-compass" class="nav-link" data-scroll-target="#intra-rater-reliability-for-the-fg-compass">Intra-rater reliability for the FG-COMPASS</a></li>
  <li><a href="#expert-rater-agreement-for-the-fg-compass" id="toc-expert-rater-agreement-for-the-fg-compass" class="nav-link" data-scroll-target="#expert-rater-agreement-for-the-fg-compass">Expert-Rater Agreement for the FG-COMPASS</a></li>
  </ul></li>
  <li><a href="#discussion" id="toc-discussion" class="nav-link" data-scroll-target="#discussion">Discussion</a>
  <ul class="collapse">
  <li><a href="#concurrent-validity-between-the-fg-compass-and-the-tgmd-2" id="toc-concurrent-validity-between-the-fg-compass-and-the-tgmd-2" class="nav-link" data-scroll-target="#concurrent-validity-between-the-fg-compass-and-the-tgmd-2">Concurrent Validity Between the FG-COMPASS and the TGMD-2</a></li>
  <li><a href="#inter-rater-analysis" id="toc-inter-rater-analysis" class="nav-link" data-scroll-target="#inter-rater-analysis">Inter-Rater Analysis</a></li>
  <li><a href="#intra-rater-reliability" id="toc-intra-rater-reliability" class="nav-link" data-scroll-target="#intra-rater-reliability">Intra-Rater Reliability</a></li>
  <li><a href="#raters-vs.-expert-agreement-for-the-fg-compass" id="toc-raters-vs.-expert-agreement-for-the-fg-compass" class="nav-link" data-scroll-target="#raters-vs.-expert-agreement-for-the-fg-compass">Raters vs.&nbsp;Expert Agreement for the FG-COMPASS</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a>
  <ul class="collapse">
  <li><a href="#implications-and-future-directions" id="toc-implications-and-future-directions" class="nav-link" data-scroll-target="#implications-and-future-directions">Implications and Future Directions</a></li>
  </ul></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations">Limitations</a>
  <ul class="collapse">
  <li><a href="#declaration-of-conflicting-interest" id="toc-declaration-of-conflicting-interest" class="nav-link" data-scroll-target="#declaration-of-conflicting-interest">Declaration of Conflicting Interest</a></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="woolever.docx"><i class="bi bi-file-word"></i>MS Word (apaquarto)</a></li><li><a href="woolever.pdf"><i class="bi bi-file-pdf"></i>PDF (apaquarto)</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">



<section id="collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass" class="level1 title">
<h1 class="title">Collecting Concurrent Validity, Expert-Rater Agreement, and Inter/Intra-Rater Reliability for the FG-COMPASS</h1>
<p><br></p>
<div class="Author">
<p>Mackinsey Woolever<sup>1</sup>, Ovande Furtado Jr<sup>1</sup>, and Jere D. Gallagher<sup>2</sup></p>
<p><sup>1</sup>Department of Kinesiology, California State University, Northridge</p>
<p><sup>2</sup>University of Pittsburgh</p>
</div>
<p><br></p>
</section>
<section id="author-note" class="level1 AuthorNote">
<h1>Author Note</h1>
<p>Mackinsey Woolever <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" class="img-fluid" width="16" alt="Orchid ID Logo: A green circle with white letters ID"> https://orcid.org/0000-0000-0000-0000</p>
<p>Ovande Furtado Jr <img src="_extensions/wjschne/apaquarto/ORCID-iD_icon-vector.svg" class="img-fluid" width="16" alt="Orchid ID Logo: A green circle with white letters ID"> https://orcid.org/0000-0003-3847-6314</p>
<p>Jere D. Gallagher is deceased.</p>
<p>Correspondence concerning this article should be addressed to Ovande Furtado Jr, Department of Kinesiology, California State University, Northridge, 18111 Nordhoff St, Northridge, CA 91330-8287, Email: ovande@gmail.com (818-564-7507)</p>
</section>
<div style="page-break-after: always;"></div>
<section id="abstract" class="level1 Abstract">
<h1>Abstract</h1>
<p>Fundamental movement skills (FMS) are the building blocks for developing specialized sports skills. In addition, fundamental movement skill competency has been linked to decreased levels of obesity and increased levels of physical activity/sports participation. This study aimed to collect evidence for concurrent validity, inter-intra-, and expert-rater reliability for the FG-COMPASS. Participants were 34 children ages 5-10 years. The agreement between the FG-COMPASS and TGMD-2 was evaluated using the intraclass correlation coefficient (ICC) and Bland-Altman analysis for LFMS, MFMS, and TFMS. The ICC for the LFMS subtest was 0.68, indicating a ‘good’ agreement between the two tests. The Bland-Altman analysis revealed a mean bias close to zero. ‘Excellent’ agreement was observed for the MFMS subtest, with an ICC of 0.89 and Bland-Altman bias close to zero. The TFMS also demonstrated ‘excellent’ agreement, with an ICC of 0.89 and Bland-Altman bias close to zero. The inter-rater reliability of the FG-COMPASS was assessed by comparing the live scores of all five raters involved in the study. Weighted kappa values ranged from 0.42 to 0.93 (M = 0.66, SD = .15) for the LFMS subtest and from 0.31 to 0.93 (M = 0.77, SD = 0.15) for the MFMS subtest. The test’s combined score (TFMS) was 0.72 (SD = 0.15). The resulting weighted kappa indicates ‘good’ agreement for the LFMS, MFMS subtests, and the total test (TFMS). The weighted kappa results for the intra-rater reliability indicate a ‘good’ agreement for LFMS (0.69), MFMS (0.70), and TFMS (0.70). The agreement between raters and the expert indicates a ‘good’ agreement for LFMS (0.64), MFMS (0.75), and TFMS (0.70). This study shows that the FG-COMPASS is a reliable and effective tool for assessing motor skills. Future research should focus on exploring any minor differences in the locomotor subtest and understand the variations in rater interpretations. Additionally, it would be beneficial to add two more skills to the locomotor subtest.</p>
<p><em>Keywords</em>: Assessment, Fundamental Movement Skills, Children, Movement Competence, Rating Scales, Assessment, Reliability, Agreement, Concurrent Validity</p>
</section>
<div style="page-break-after: always;"></div>
<section id="collecting-concurrent-validity-expert-rater-agreement-and-interintra-rater-reliability-for-the-fg-compass-1" class="level1">
<h1>Collecting Concurrent Validity, Expert-Rater Agreement, and Inter/Intra-Rater Reliability for the FG-COMPASS</h1>
<p>The acquisition of basic movement skills (FMS) holds significant importance for young children, as it has the potential to impact their development and lifestyle in both positive and negative ways. The level of motor competence is crucial to an individual’s engagement in physical activities <span class="citation" data-cites="castelli2007">(<a href="#ref-castelli2007" role="doc-biblioref">Castelli &amp; Valley, 2007</a>)</span>. Previous research has demonstrated a favorable correlation between perceived motor competence and proficiency in fundamental motor skills (FMS) among children and adolescents <span class="citation" data-cites="woods2007">(<a href="#ref-woods2007" role="doc-biblioref">Woods et al., 2007</a>)</span>. There is a favorable correlation between engagement in physical activity and the development of fundamental movement skills (FMS), particularly when the activities are of moderate to vigorous intensity <span class="citation" data-cites="bellows2013 fisher2005 lemos2012 mckenzie2002">(<a href="#ref-bellows2013" role="doc-biblioref">Bellows et al., 2013</a>; <a href="#ref-fisher2005" role="doc-biblioref">Fisher et al., 2005</a>; <a href="#ref-lemos2012" role="doc-biblioref">Lemos, 2012</a>; <a href="#ref-mckenzie2002" role="doc-biblioref">McKenzie et al., 2002</a>)</span>. Additionally, there is an inverse relationship between physical activity involvement and the prevalence of obesity <span class="citation" data-cites="bayer2009 graf2004 lopes2012">(<a href="#ref-bayer2009" role="doc-biblioref">Bayer et al., 2009</a>; <a href="#ref-graf2004" role="doc-biblioref">Graf et al., 2004</a>; <a href="#ref-lopes2012" role="doc-biblioref">Lopes et al., 2012</a>)</span>. Research has indicated a correlation between inadequate motor skill competence in children and reduced physical activity levels <span class="citation" data-cites="fisher2005 mckenzie2002">(<a href="#ref-fisher2005" role="doc-biblioref">Fisher et al., 2005</a>; <a href="#ref-mckenzie2002" role="doc-biblioref">McKenzie et al., 2002</a>)</span>. Furthermore, this lack of motor skill proficiency has been associated with an increased likelihood of being overweight or obese <span class="citation" data-cites="cliff2012">(<a href="#ref-cliff2012" role="doc-biblioref">Cliff et al., 2012</a>)</span>.</p>
<p>Assessing the development of fundamental movement skills (FMS) is crucial for children in preschool and primary school, as these skills significantly influence their overall development and well-being throughout their lifespan. According <span class="citation" data-cites="ulrich2000">Ulrich (<a href="#ref-ulrich2000" role="doc-biblioref">2000</a>)</span>, early childhood education tends to neglect the development of gross motor abilities. Assessment instruments are specifically developed to identify variations in motor development that can span a spectrum of severity, encompassing slight and significant delays. Failure to address delays in motor skill development promptly may impede the subsequent development of gross motor abilities <span class="citation" data-cites="ulrich2000">(<a href="#ref-ulrich2000" role="doc-biblioref">Ulrich, 2000</a>)</span> and may affect the acquisition of specialized skills <span class="citation" data-cites="gabbard2021">(<a href="#ref-gabbard2021" role="doc-biblioref">Gabbard, 2021</a>)</span>. According to <span class="citation" data-cites="provost2000">Provost et al. (<a href="#ref-provost2000" role="doc-biblioref">2000</a>)</span>, a developmental delay is a discrepancy of 25% or greater between a child’s chronological age and developmental age. Early detection of motor delay enables practitioners, parents, and educators to employ intervention measures to assist the child. A range of instruments exists for assessing fundamental movement skills, as highlighted by <span class="citation" data-cites="cools2009">Cools et al. (<a href="#ref-cools2009" role="doc-biblioref">2009</a>)</span>. Nevertheless, it is important to note that these assessment tools are often not intended for real-time assessment by a single practitioner. Typically, test administrators are required to record the performances and then evaluate them. Developing an assessment tool that enables professionals to assess children’s FMS proficiency without needing performance recording will enhance convenience.</p>
<p>It is essential to have a practical assessment instrument to assess gross motor development in school-age children. This helps identify any potential motor delays and ensures typical development. The Furtado-Gallagher Child Observational Movement Pattern Assessment System (FG-COMPASS) was developed to fill this gap as it relies on only three performance criteria to evaluate FMS performance <span class="citation" data-cites="furtado2012">(<a href="#ref-furtado2012" role="doc-biblioref">Furtado &amp; Gallagher, 2012</a>)</span>. To date, there have been no attempts to compare the results of the FG-COMPASS with those of a criterion measure. In addition, while the FG-COMPASS has demonstrated evidence of both inter- and intra-rater reliability, the agreement data utilized in these studies were obtained through video analysis rather than live performances <span class="citation" data-cites="furtado2012 furtado2018">(<a href="#ref-furtado2012" role="doc-biblioref">Furtado &amp; Gallagher, 2012</a>, <a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span>. Therefore, this study aimed to collect criterion-related (concurrent) validity for the FG-COMPASS by comparing its results with the results of the TGMD-2 <span class="citation" data-cites="ulrich2000">(<a href="#ref-ulrich2000" role="doc-biblioref">Ulrich, 2000</a>)</span>, a popular instrument used to assess FMS in children. In addition, this study sought to collect further inter-, intra-, and expert-rater reliability evidence for the FG-COMPASS from live assessments. Several hypotheses were proposed for this study. We anticipated that there would be at least a ‘good’ agreement (ICC/kappa scores above 0.74) for the locomotor (LFMS), manipulative (MFMS), and total test (TFMS) when investigating concurrent validity, inter- and intra-rater reliability, and expert-rater reliability for the FG-COMPASS.</p>
</section>
<section id="materials-and-methods" class="level1">
<h1>Materials and Methods</h1>
<section id="participants" class="level2">
<h2 data-anchor-id="participants">Participants</h2>
<p>A convenient sampling method was used to recruit participants for this study. After Institutional Review Board approval, 41 children between the ages of 5 and 10 were recruited. However, only 34 children, 22 girls (M = 8.14, SD = 1.78) and 12 boys (M = 8.44, SD = 1.49), participated fully. Three participants dropped out independently; two never attended the assessment sessions; one was injured before the assessment, and one child moved out of the state during the data collection. Informed consent was obtained from each participant’s parents or legal guardians before their involvement in the study. One randomly selected kindergarten through fourth-grade classroom received a recruitment packet to control for an even distribution of age ranges. Recruitment packets were given to additional classrooms if no consent forms were returned. A participant was excluded from the study if he/she: 1) was younger than 5 years or older than 10 years and 11 months; 2) had developmental delays or disabilities that may have affected their motor performance; 3) had no parental or verbal consent; or 4) had a “yes” response on any of the first five Physical Activity Readiness-Questionnaire (PAR-Q) questions <span class="citation" data-cites="adams1999">(<a href="#ref-adams1999" role="doc-biblioref">Adams, 1999</a>)</span>.</p>
</section>
<section id="measures" class="level2">
<h2 data-anchor-id="measures">Measures</h2>
<section id="tgmd-2" class="level3">
<h3 data-anchor-id="tgmd-2">TGMD-2</h3>
<p>The TGMD-2 <span class="citation" data-cites="ulrich2000">(<a href="#ref-ulrich2000" role="doc-biblioref">Ulrich, 2000</a>)</span>, served as the gold standard for the concurrent validity analysis. This tool evaluates twelve gross motor skills, divided into two categories: six concerning locomotion and six related to object manipulation, suitable for children aged between 3 and 10 years. The TGMD-2 assesses various performance criteria that focus on different body components including the arms, legs, and trunk. For instance, one criterion for hopping is that the “arms be flexed and swing forward to generate force.” Each child is given two attempts to demonstrate each skill; a successful attempt awards a score of 1, while unsuccessful attempts receive a score of 0. Following the two trials for each skill, the scores are totaled to find the overall raw score for each subtest. These raw scores are then converted to standard scores, enabling comparison to normative data. By analyzing the standard scores from both subtests, researchers can determine age equivalents and percentiles. These standard scores, when combined, form a gross motor quotient value.</p>
<p>Several studies have addressed the validity and reliability of the TGMD-2. The instrument demonstrates strong construct validity, effectively measuring the fundamental theoretical construct of gross motor development <span class="citation" data-cites="ulrich2000">(<a href="#ref-ulrich2000" role="doc-biblioref">Ulrich, 2000</a>)</span>. Its concurrent validity is supported through correlations with other established motor skill assessments, such as the Movement Assessment Battery for Children (MABC) <span class="citation" data-cites="cools2009">(<a href="#ref-cools2009" role="doc-biblioref">Cools et al., 2009</a>)</span>. High test-retest reliability of the TGMD-2 is reported, with coefficients frequently exceeding 0.90 <span class="citation" data-cites="valentini2004">(<a href="#ref-valentini2004" role="doc-biblioref">Valentini &amp; Rudisill, 2004</a>)</span>. The test maintains good internal consistency, evidenced by Cronbach’s alpha values generally above 0.80 for both the locomotion and object manipulation subtests <span class="citation" data-cites="wiart2001">(<a href="#ref-wiart2001" role="doc-biblioref">Wiart &amp; Darrah, 2001</a>)</span>. The TGMD-2 has also been adapted and validated in different cultural contexts, indicating its utility across various populations <span class="citation" data-cites="barnett2009">(<a href="#ref-barnett2009" role="doc-biblioref">Barnett et al., 2009</a>)</span>. The standardization process involved a representative sample of children in the United States, ensuring the relevance of the normative data for the target age group.</p>
</section>
<section id="fg-compass" class="level3">
<h3 data-anchor-id="fg-compass">FG-COMPASS</h3>
<p>The FG-COMPASS is a tool created to assess the gross motor skills of children aged 5 to 10 years. It evaluates eight skills, including three pertaining to locomotion and five to object manipulation. In the development of FG-COMPASS, <span class="citation" data-cites="furtado2012">Furtado and Gallagher (<a href="#ref-furtado2012" role="doc-biblioref">2012</a>)</span> introduced a novel approach to constructing FMS rating scales. This method, detailed further in works by <span class="citation" data-cites="perez2018">Perez (<a href="#ref-perez2018" role="doc-biblioref">2018</a>)</span> and <span class="citation" data-cites="furtado2012">Furtado and Gallagher (<a href="#ref-furtado2012" role="doc-biblioref">2012</a>)</span>, utilizes only key performance criteria arranged in a decision tree. Figure 1 depicts the decision tree for the ‘Overhand Throw’ skill, demonstrating three types of nodes: decision nodes, which pose questions; chance nodes, offering ‘yes or no’ options; and end nodes, which indicate levels.</p>
<p>Despite the availability of many performance criteria for each skill, only three are selected to create the decision tree, which is then formed through questions derived from these criteria. A particular instance of this can be observed in Figure 1, where a question at the top decision node aims to differentiate between levels 1 and 4. A ‘yes’ at the chance node directs to the right pathway, prompting a follow-up question to confirm if the individual exhibits a level 4 proficiency in overhand throws. If the answer is ‘no’, the rating settles at level 3.</p>
<p>A similar process occurs on the left side of the tree, this time to assess for level 1 proficiency.This approach allows for a simplified evaluation of live performances of fundamental movement skills, restricting the assessment to just two performance criteria when determining skill proficiency levels. It enjoys support from several studies validating its efficacy and reliability, including evidence for content-related validity <span class="citation" data-cites="furtado2004">(<a href="#ref-furtado2004" role="doc-biblioref">Furtado, 2004</a>)</span>, expert-rater agreement <span class="citation" data-cites="furtado2012 furtado2018">(<a href="#ref-furtado2012" role="doc-biblioref">Furtado &amp; Gallagher, 2012</a>, <a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span>, and intra- and inter-rater reliability <span class="citation" data-cites="furtado2018">(<a href="#ref-furtado2018" role="doc-biblioref">Furtado &amp; Gallagher, 2018</a>)</span>.</p>
<p>[figure 1 here]</p>
</section>
</section>
<section id="research-assistants" class="level2">
<h2 data-anchor-id="research-assistants">Research Assistants</h2>
<p>Sixteen undergraduate students studying kinesiology were selected as research assistants for the study. Ten students were chosen to work as raters in the assessment of gross motor skills, with a random assignment of five raters per instrument: TGMD-2 and FG-COMPASS. The remaining students were allocated roles as test administrators — three for TGMD-2 and two for FG-COMPASS — with the exception of one individual who was assigned to edit videos remotely, hence not requiring presence at the research site.</p>
<p>Before initiating data collection, all participants underwent training tailored to their designated roles and respective instruments. This involved multiple sessions aimed at acquainting them with the necessary skills, including instruction on the setup for skills assessment, demonstrating tasks accurately, and the appropriate use and positioning of cameras for recording. The training ensured that both raters and test administrators were well-prepared to carry out their tasks effectively during the data collection phase.</p>
</section>
<section id="procedures" class="level2">
<h2 data-anchor-id="procedures">Procedures</h2>
<section id="data-collection" class="level3">
<h3 data-anchor-id="data-collection">Data collection</h3>
<p>The TGMD-2 and the FG-COMPASS, although assessing the same construct, have distinct differences in their methods of evaluation. Despite these differences, there were common procedures followed in administering both tests. The assessments were conducted during the morning or lunch recess periods, ensuring that all the student participants were able to complete both tests.</p>
<p>Before the onset of data collection, the primary investigator assigned identification numbers to the participants to maintain order and organization. Participants, upon reaching the test location, were guided to either the TGMD-2 or the FG-COMPASS stations as determined by a randomized list. This setup was revisited weekly to negate potential learning effects stemming from repeated measurement of the same skill. After concluding the initial test at one of the stations, participants moved to the alternate station for further assessment. In certain instances, participants were asked to demonstrate multiple skills across both stations, thereby alternating between them as needed.</p>
<p>Weekly, the administrators overseeing the TGMD-2 station visited the site to carry out the assessments as per the directives detailed in the user manual by <span class="citation" data-cites="ulrich2000">Ulrich (<a href="#ref-ulrich2000" role="doc-biblioref">2000</a>)</span>. All skill performances were videotaped. Subsequently, the TGMD-2 raters were called to the lab to assess the performances through the recorded videos. The FG-COMPASS raters evaluated the participants directly on-site, though these performances were also recorded to allow for intra-rater reliability analysis. The participants were accorded one practice trial followed by three test trials for each skill.</p>
</section>
</section>
<section id="data-analysis" class="level2">
<h2 data-anchor-id="data-analysis">Data Analysis</h2>
<p>Concurrent validity was assessed using the intraclass correlation coefficient (ICC, 2, k) and Bland-Altman plots. The reliability of the FG-COMPASS, both in terms of inter- and intra-rater consistency, as well as the agreement between the expert and raters, was examined using weighted kappa statistics.</p>
<p>The ICC is designed to evaluate the reliability of ratings by comparing the variation of different ratings for the same participant to the total variation across all ratings and participants <span class="citation" data-cites="mcgraw1996">(<a href="#ref-mcgraw1996" role="doc-biblioref">McGraw &amp; Wong, 1996</a>)</span>. The Bland-Altman method involves determining the agreement between two quantitative measurements by studying the average difference and setting agreement limits, a strategy preferred over correlation techniques <span class="citation" data-cites="bland1986 giavarina2015">(<a href="#ref-bland1986" role="doc-biblioref">Bland &amp; Altman, 1986</a>; <a href="#ref-giavarina2015" role="doc-biblioref">Giavarina, 2015</a>)</span>.</p>
<p>The weighted kappa index is recommended for use when more than two coders are independently classifying an entity into three or more separate categories at an ordinal level, assigning different weights based on the degree of disagreement <span class="citation" data-cites="fleiss1973">(<a href="#ref-fleiss1973" role="doc-biblioref">Fleiss &amp; Cohen, 1973</a>)</span>. Different from kappa, the weighted version considers the degree of disagreement in its calculation. The interpretation of weighted kappa and ICC values followed this scheme: above 0.75 indicated excellent agreement; values between 0.74 and 0.60 were good; values between 0.59 and 0.40 were fair, and values below 0.40 were poor <span class="citation" data-cites="cicchetti1994">(<a href="#ref-cicchetti1994" role="doc-biblioref">Cicchetti, 1994</a>)</span>.</p>
<p>A cross-sectional design was utilized in this study, and all statistical analyses were conducted using the statistical package jamovi <span class="citation" data-cites="jamovi233">(<a href="#ref-jamovi233" role="doc-biblioref">The jamovi project, 2022</a>)</span>.</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<section id="concurrent-validity" class="level2">
<h2 data-anchor-id="concurrent-validity">Concurrent Validity</h2>
<p>The agreement between the FG-COMPASS and TGMD-2 (see Table&nbsp;1) was evaluated using the intraclass correlation coefficient and Bland-Altman analysis for LFMS, MFMS, and TFMS. The ICC for the LFMS subtest was 0.68, indicating a ‘good’ agreement between the two tests. The Bland-Altman analysis revealed a mean bias close to zero. ‘Excellent’ agreement was observed for the MFMS subtest, with an ICC of 0.89 and Bland-Altman bias close to zero. The TFMS also demonstrated ‘excellent’ agreement, with an ICC of 0.89 and Bland-Altman bias close to zero.</p>
<div class="cell" data-apa-cap="Concurrent Validity Analysis for FG-COMPASS" data-apa-note="ICC: Intraclass Correlation Coefficient (ICC, 2, k). Bias: Mean difference between the two methods. LLA &amp; ULA: 95% lower and upper limits of agreement in the Bland-Altman analysis.<br/> (*): p < 0.05.<br/> (**): p < 0.001.">
<div id="apatb-table1" class="FigureTitle">
<p>Table&nbsp;1</p>
</div>
<div class="Caption">
<p>Concurrent Validity Analysis for FG-COMPASS</p>
</div>
<div class="FigureWithNote">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 26%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>ICC</th>
<th>F-Statistic (p-value)</th>
<th>Bias</th>
<th>LLA</th>
<th>ULA</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Locomotor</strong></td>
<td>0.68</td>
<td>3.05 (*)</td>
<td>1.73e−16</td>
<td>−1.95</td>
<td>1.95</td>
</tr>
<tr class="even">
<td><strong>Manipulative</strong></td>
<td>0.89</td>
<td>8.85 (**)</td>
<td>2.60e−16</td>
<td>−1.25</td>
<td>1.25</td>
</tr>
<tr class="odd">
<td><strong>Total test</strong></td>
<td>0.89</td>
<td>9.00 (**)</td>
<td>−2.53e−16</td>
<td>−1.24</td>
<td>1.24</td>
</tr>
</tbody>
</table>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. ICC:&nbsp;Intraclass Correlation Coefficient (ICC, 2, k). Bias:&nbsp;Mean difference between the two methods. LLA &amp; ULA:&nbsp;95% lower and upper limits of agreement in the Bland-Altman analysis.<br> (*):&nbsp;p &lt; 0.05.<br> (**):&nbsp;p &lt; 0.001.</p>
</div>
</div>
</div>
</section>
<section id="inter-rater-reliability" class="level2">
<h2 data-anchor-id="inter-rater-reliability">Inter-Rater Reliability</h2>
<p>The inter-rater reliability of the FG-COMPASS was assessed by comparing the live scores of all five raters involved in the study (see Table&nbsp;2). Weighted kappa values were computed for each pair of raters, and then the mean was calculated to provide a single index of reliability <span class="citation" data-cites="light1971">(<a href="#ref-light1971" role="doc-biblioref">Light, 1971</a>)</span>. Weighted kappa values ranged from 0.42 to 0.93 (M = 0.66 SD = .15) for the LFMS subtest and from 0.31 to 0.93 (M = 0.77 SD = 0.15) for the MFMS subtest. The test’s combined score (TFMS) was 0.72 (SD = 0.15). The resulting weighted kappa indicates ‘good’ agreement for the LFMS, MFMS subtests, and the total test (TFMS).</p>
<div class="cell" data-apa-cap="Weighted Kappa Statistics for the Inter-Rater Analysis" data-apa-note="LFMS = Locomotor Subtest. MFMS = Manipulative Subtest. TFMS = Locomotor and Manipulative scores combined. <br/> Asterisks indicate major disagreement between rater 5 and all other raters.">
<div id="apatb-table2" class="FigureTitle">
<p>Table&nbsp;2</p>
</div>
<div class="Caption">
<p>Weighted Kappa Statistics for the Inter-Rater Analysis</p>
</div>
<div class="FigureWithNote">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 5%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Skill</th>
<th>1x2</th>
<th>1x3</th>
<th>1x4</th>
<th>1x5</th>
<th>2x3</th>
<th>2x4</th>
<th>2x5</th>
<th>3x4</th>
<th>3x5</th>
<th>4x5</th>
<th>Mean</th>
<th>SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>LFMS</strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><strong>.66</strong></td>
<td>.15</td>
</tr>
<tr class="even">
<td></td>
<td>Hop</td>
<td>.56</td>
<td>.43</td>
<td>.43</td>
<td>.50</td>
<td>.42</td>
<td>.49</td>
<td>.46</td>
<td>.53</td>
<td>.64</td>
<td>.52</td>
<td>.50</td>
<td>.07</td>
</tr>
<tr class="odd">
<td></td>
<td>Jump</td>
<td>.93</td>
<td>.91</td>
<td>.70</td>
<td>.65</td>
<td>.84</td>
<td>.73</td>
<td>.62</td>
<td>.61</td>
<td>.61</td>
<td>.69</td>
<td>.73</td>
<td>.12</td>
</tr>
<tr class="even">
<td></td>
<td>Skip</td>
<td>.78</td>
<td>.74</td>
<td>.60</td>
<td>.63</td>
<td>.87</td>
<td>.77</td>
<td>.76</td>
<td>.69</td>
<td>.71</td>
<td>.83</td>
<td>.74</td>
<td>.08</td>
</tr>
<tr class="odd">
<td><strong>MFMS</strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><strong>.77</strong></td>
<td>.15</td>
</tr>
<tr class="even">
<td></td>
<td>Throw</td>
<td>.85</td>
<td>.79</td>
<td>.85</td>
<td>.45*</td>
<td>.80</td>
<td>.73</td>
<td>.35*</td>
<td>.71</td>
<td>.31*</td>
<td>.40*</td>
<td>.62</td>
<td>.22</td>
</tr>
<tr class="odd">
<td></td>
<td>Kick</td>
<td>.83</td>
<td>.68</td>
<td>.64</td>
<td>.82</td>
<td>.63</td>
<td>.59</td>
<td>.73</td>
<td>.50</td>
<td>.72</td>
<td>.64</td>
<td>.68</td>
<td>.10</td>
</tr>
<tr class="even">
<td></td>
<td>Dribble</td>
<td>.86</td>
<td>.87</td>
<td>.83</td>
<td>.92</td>
<td>.88</td>
<td>.84</td>
<td>.91</td>
<td>.88</td>
<td>.93</td>
<td>.93</td>
<td>.89</td>
<td>.04</td>
</tr>
<tr class="odd">
<td></td>
<td>Catch</td>
<td>.87</td>
<td>.91</td>
<td>.87</td>
<td>.90</td>
<td>.83</td>
<td>.84</td>
<td>.90</td>
<td>.80</td>
<td>.80</td>
<td>.89</td>
<td>.86</td>
<td>.04</td>
</tr>
<tr class="even">
<td></td>
<td>Strike</td>
<td>.81</td>
<td>.80</td>
<td>.72</td>
<td>.72</td>
<td>.87</td>
<td>.80</td>
<td>.80</td>
<td>.69</td>
<td>.78</td>
<td>.79</td>
<td>.78</td>
<td>.05</td>
</tr>
<tr class="odd">
<td><strong>TFMS</strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td><strong>.72</strong></td>
<td>.15</td>
</tr>
</tbody>
</table>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. LFMS = Locomotor Subtest. MFMS = Manipulative Subtest. TFMS = Locomotor and Manipulative scores combined. <br> Asterisks indicate major disagreement between rater 5 and all other raters.</p>
</div>
</div>
</div>
</section>
<section id="intra-rater-reliability-for-the-fg-compass" class="level2">
<h2 data-anchor-id="intra-rater-reliability-for-the-fg-compass">Intra-rater reliability for the FG-COMPASS</h2>
<p>We evaluated the consistency of ratings by comparing live assessments with those obtained through video assessments (see Table&nbsp;3). Of particular interest is ‘IR1’, which compares the ratings obtained from live assessments with those from recorded performances (time 1), which took place one week after the live assessment at the site. Additionally, we included ratings from a second video assessment and compared it with the live assessment (IR2) and the first video assessment (IR3). In Table&nbsp;4, we provide the mean and standard deviation scores for each intra-rater comparison across all five raters. Scores ranged from 0.50 to 0.89, indicating agreement from ‘fair’ to ‘excellent’ <span class="citation" data-cites="cicchetti1994">(<a href="#ref-cicchetti1994" role="doc-biblioref">Cicchetti, 1994</a>)</span>.</p>
<div style="page-break-after: always;"></div>
<div class="cell" data-apa-cap="Intra-Rater Agreement Measured by Weighted Kappa Coefficients Across Different Skills" data-apa-note="Quadratic weighted kappa values range from -1 to 1. IR1, IR2, IR3 represent three different comparison pairs: IR1 compares the ratings from the live performances with the recorded video (time 1), IR2 compares ratings from the live performances with the recorded video (time 2), and IR3 compares the ratings from the recorded performances from time 1 and time 2. Sample sizes for each skill are provided in parentheses next to the skill name. Rater 1 to Rater 5 represent five different individuals who rated the performances.">
<div id="apatb-table3" class="FigureTitle">
<p>Table&nbsp;3</p>
</div>
<div class="Caption">
<p>Intra-Rater Agreement Measured by Weighted Kappa Coefficients Across Different Skills</p>
</div>
<div class="FigureWithNote">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 4%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Rater 1</th>
<th>Rater 2</th>
<th>Rater 3</th>
<th>Rater 4</th>
<th>Rater 5</th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>IR1</td>
<td>IR2</td>
<td>IR3</td>
<td>IR1</td>
<td>IR2</td>
<td>IR3</td>
<td>IR1</td>
<td>IR2</td>
<td>IR3</td>
<td>IR1</td>
<td>IR2</td>
<td>IR3</td>
<td>IR1</td>
<td>IR2</td>
<td>IR3</td>
</tr>
<tr class="even">
<td>Hop (17)</td>
<td>0.72</td>
<td>0.83</td>
<td>0.89</td>
<td>0.44</td>
<td>0.55</td>
<td>0.75</td>
<td>0.64</td>
<td>0.62</td>
<td>0.88</td>
<td>0.69</td>
<td>0.40</td>
<td>0.62</td>
<td>0.84</td>
<td>0.62</td>
<td>0.80</td>
</tr>
<tr class="odd">
<td>Jump (18)</td>
<td>0.56</td>
<td>0.49</td>
<td>0.83</td>
<td>0.46</td>
<td>0.68</td>
<td>0.39</td>
<td>0.74</td>
<td>0.38</td>
<td>0.49</td>
<td>0.56</td>
<td>0.28</td>
<td>0.56</td>
<td>0.67</td>
<td>0.67</td>
<td>1.00</td>
</tr>
<tr class="even">
<td>Skip (18)</td>
<td>0.96</td>
<td>0.96</td>
<td>1.00</td>
<td>0.94</td>
<td>0.78</td>
<td>0.86</td>
<td>0.92</td>
<td>0.86</td>
<td>0.89</td>
<td>0.51</td>
<td>0.68</td>
<td>0.86</td>
<td>0.66</td>
<td>0.52</td>
<td>0.83</td>
</tr>
<tr class="odd">
<td>Throw (18)</td>
<td>0.80</td>
<td>0.52</td>
<td>0.53</td>
<td>0.63</td>
<td>0.62</td>
<td>0.97</td>
<td>0.52</td>
<td>0.54</td>
<td>0.60</td>
<td>0.69</td>
<td>0.76</td>
<td>0.70</td>
<td>0.54</td>
<td>0.66</td>
<td>0.86</td>
</tr>
<tr class="even">
<td>Kick (19)</td>
<td>0.72</td>
<td>0.68</td>
<td>0.78</td>
<td>0.66</td>
<td>0.60</td>
<td>0.76</td>
<td>0.80</td>
<td>0.70</td>
<td>0.74</td>
<td>0.74</td>
<td>0.64</td>
<td>0.72</td>
<td>0.64</td>
<td>0.62</td>
<td>0.80</td>
</tr>
<tr class="odd">
<td>Dribble (17)</td>
<td>0.86</td>
<td>0.80</td>
<td>0.82</td>
<td>0.70</td>
<td>0.78</td>
<td>0.86</td>
<td>0.66</td>
<td>0.60</td>
<td>0.82</td>
<td>0.76</td>
<td>0.68</td>
<td>0.74</td>
<td>0.60</td>
<td>0.64</td>
<td>0.68</td>
</tr>
<tr class="even">
<td>Catch (20)</td>
<td>0.68</td>
<td>0.62</td>
<td>0.86</td>
<td>0.86</td>
<td>0.66</td>
<td>0.80</td>
<td>0.76</td>
<td>0.78</td>
<td>0.82</td>
<td>0.66</td>
<td>0.60</td>
<td>0.78</td>
<td>0.84</td>
<td>0.88</td>
<td>0.88</td>
</tr>
<tr class="odd">
<td>Strike (20)</td>
<td>0.62</td>
<td>0.56</td>
<td>0.60</td>
<td>0.74</td>
<td>0.70</td>
<td>0.70</td>
<td>0.64</td>
<td>0.64</td>
<td>0.64</td>
<td>0.74</td>
<td>0.68</td>
<td>0.68</td>
<td>0.70</td>
<td>0.62</td>
<td>0.78</td>
</tr>
</tbody>
</table>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Quadratic weighted kappa values range from -1 to 1. IR1, IR2, IR3 represent three different comparison pairs:&nbsp;IR1 compares the ratings from the live performances with the recorded video (time 1), IR2 compares ratings from the live performances with the recorded video (time 2), and IR3 compares the ratings from the recorded performances from time 1 and time 2. Sample sizes for each skill are provided in parentheses next to the skill name. Rater 1 to Rater 5 represent five different individuals who rated the performances.</p>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
<div class="cell" data-apa-cap="Summary of Quadratic Weighted Kappa for Intra-Rater Comparisons Across Motor Skills" data-apa-note="IR1, IR2, IR3: Represent different inter-rater comparisons (e.g., live vs. video 1, live vs. video 2, video 1 vs. video 2). Mean: The average of the quadratic weighted kappa values for each scenario across all raters and skills. SD: The standard deviation of the quadratic weighted kappa values for each scenario across all raters and skills.">
<div id="apatb-table4" class="FigureTitle">
<p>Table&nbsp;4</p>
</div>
<div class="Caption">
<p>Summary of Quadratic Weighted Kappa for Intra-Rater Comparisons Across Motor Skills</p>
</div>
<div class="FigureWithNote">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th>Skill</th>
<th>IR1 Mean (SD)</th>
<th>IR2 Mean (SD)</th>
<th>IR3 Mean (SD)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>LFMS</td>
<td><strong>0.69</strong></td>
<td>0.62</td>
<td>0.78</td>
</tr>
<tr class="even">
<td>Hop</td>
<td>0.67 (0.13)</td>
<td>0.60 (0.14)</td>
<td>0.79 (0.10)</td>
</tr>
<tr class="odd">
<td>Jump</td>
<td>0.60 (0.10)</td>
<td>0.50 (0.16)</td>
<td>0.65 (0.23)</td>
</tr>
<tr class="even">
<td>Skip</td>
<td>0.80 (0.18)</td>
<td>0.76 (0.15)</td>
<td>0.89 (0.06)</td>
</tr>
<tr class="odd">
<td>MFMS</td>
<td><strong>0.70</strong></td>
<td>0.66</td>
<td>0.76</td>
</tr>
<tr class="even">
<td>Throw</td>
<td>0.64 (0.10)</td>
<td>0.62 (0.09)</td>
<td>0.73 (0.16)</td>
</tr>
<tr class="odd">
<td>Kick</td>
<td>0.71 (0.06)</td>
<td>0.65 (0.04)</td>
<td>0.76 (0.03)</td>
</tr>
<tr class="even">
<td>Dribble</td>
<td>0.72 (0.09)</td>
<td>0.70 (0.08)</td>
<td>0.78 (0.06)</td>
</tr>
<tr class="odd">
<td>Catch</td>
<td>0.76 (0.08)</td>
<td>0.71 (0.11)</td>
<td>0.83 (0.04)</td>
</tr>
<tr class="even">
<td>Strike</td>
<td>0.69 (0.05)</td>
<td>0.64 (0.05)</td>
<td>0.68 (0.06)</td>
</tr>
<tr class="odd">
<td>TFMS</td>
<td><strong>0.70</strong></td>
<td>0.64</td>
<td>0.77</td>
</tr>
</tbody>
</table>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. IR1, IR2, IR3:&nbsp;Represent different inter-rater comparisons (e.g., live vs.&nbsp;video 1, live vs.&nbsp;video 2, video 1 vs.&nbsp;video 2). Mean:&nbsp;The average of the quadratic weighted kappa values for each scenario across all raters and skills. SD:&nbsp;The standard deviation of the quadratic weighted kappa values for each scenario across all raters and skills.</p>
</div>
</div>
</div>
</section>
<section id="expert-rater-agreement-for-the-fg-compass" class="level2">
<h2 data-anchor-id="expert-rater-agreement-for-the-fg-compass">Expert-Rater Agreement for the FG-COMPASS</h2>
<p>The study aimed to assess the level of agreement between raters and expert ratings for the FG-COMPASS. The live ratings of five raters were compared with the expert’s video scores. The results showed that the level of agreement varied across the skills assessed. For ‘Hop’, the agreement ranged from ‘fair’ to ‘excellent’, with a mean kappa value of 0.67. For ‘Skip’, the agreement was more varied, with kappa values ranging from ‘poor’ to ‘excellent’. In the MFMS subtest, the agreement was considered ‘excellent’. For ‘Throw’, the agreement ranged from good to excellent, with a mean kappa value of 0.75. For ‘Dribble’, all raters showed ‘excellent’ agreement, with kappa values ranging from 0.77 to 0.94 and a mean kappa of 0.86. For ‘Catch’, the agreement was ‘excellent’, with a mean kappa value of 0.83. For ‘Strike’, the agreement was ‘fair’ to ‘good’ with kappa values ranging from 0.40 to 0.61 and a mean kappa of 0.51. Considering all skills (TFMS), the mean kappa value was 0.70, indicating ‘good’ agreement across all skills when considering all raters.</p>
<div class="cell" data-apa-cap="Weighted Kappa Scores between Raters and an Expert" data-apa-note="Kappa scores are displayed without 95% confidence intervals. Mean and SD columns represent the average kappa score and dispersion for each skill, respectively. For LFMS, MFMS, and TFMS, these represent averages of the skills under each category. Sample sizes for each skill are indicated in parentheses after the skill name.">
<div id="apatb-table5" class="FigureTitle">
<p>Table&nbsp;5</p>
</div>
<div class="Caption">
<p>Weighted Kappa Scores between Raters and an Expert</p>
</div>
<div class="FigureWithNote">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Skill</th>
<th style="text-align: left;">Rater 1</th>
<th style="text-align: left;">Rater 2</th>
<th style="text-align: left;">Rater 3</th>
<th style="text-align: left;">Rater 4</th>
<th style="text-align: left;">Rater 5</th>
<th style="text-align: left;">Mean</th>
<th style="text-align: left;">SD</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">LFMS</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>0.64</strong></td>
<td style="text-align: left;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Hop (17)</td>
<td style="text-align: left;">0.71</td>
<td style="text-align: left;">0.77</td>
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">0.65</td>
<td style="text-align: left;">0.70</td>
<td style="text-align: left;">0.67</td>
<td style="text-align: left;">0.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Jump (18)</td>
<td style="text-align: left;">0.74</td>
<td style="text-align: left;">0.83</td>
<td style="text-align: left;">0.78</td>
<td style="text-align: left;">0.75</td>
<td style="text-align: left;">0.57</td>
<td style="text-align: left;">0.73</td>
<td style="text-align: left;">0.09</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Skip (18)</td>
<td style="text-align: left;">0.67</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">0.59</td>
<td style="text-align: left;">0.29</td>
<td style="text-align: left;">0.35</td>
<td style="text-align: left;">0.53</td>
<td style="text-align: left;">0.18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">MFMS</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;">0.74</td>
<td style="text-align: left;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Throw (19)</td>
<td style="text-align: left;">0.92</td>
<td style="text-align: left;">0.79</td>
<td style="text-align: left;">0.65</td>
<td style="text-align: left;">0.71</td>
<td style="text-align: left;">0.69</td>
<td style="text-align: left;"><strong>0.75</strong></td>
<td style="text-align: left;">0.10</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Kick (19)</td>
<td style="text-align: left;">0.82</td>
<td style="text-align: left;">0.70</td>
<td style="text-align: left;">0.51</td>
<td style="text-align: left;">0.78</td>
<td style="text-align: left;">0.82</td>
<td style="text-align: left;">0.73</td>
<td style="text-align: left;">0.12</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Dribble (17)</td>
<td style="text-align: left;">0.91</td>
<td style="text-align: left;">0.77</td>
<td style="text-align: left;">0.94</td>
<td style="text-align: left;">0.77</td>
<td style="text-align: left;">0.89</td>
<td style="text-align: left;">0.86</td>
<td style="text-align: left;">0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;"></td>
<td style="text-align: left;">Catch (20)</td>
<td style="text-align: left;">0.89</td>
<td style="text-align: left;">0.84</td>
<td style="text-align: left;">0.83</td>
<td style="text-align: left;">0.82</td>
<td style="text-align: left;">0.76</td>
<td style="text-align: left;">0.83</td>
<td style="text-align: left;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;">Strike (19)</td>
<td style="text-align: left;">0.61</td>
<td style="text-align: left;">0.57</td>
<td style="text-align: left;">0.50</td>
<td style="text-align: left;">0.49</td>
<td style="text-align: left;">0.40</td>
<td style="text-align: left;">0.51</td>
<td style="text-align: left;">0.07</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TFMS</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>0.70</strong></td>
<td style="text-align: left;">0.10</td>
</tr>
</tbody>
</table>
<div class="FigureNote" data-custom-style="FigureNote">
<p><em>Note</em>. Kappa scores are displayed without 95% confidence intervals. Mean and SD columns represent the average kappa score and dispersion for each skill, respectively. For LFMS, MFMS, and TFMS, these represent averages of the skills under each category. Sample sizes for each skill are indicated in parentheses after the skill name.</p>
</div>
</div>
</div>
</section>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<p>This study aimed to establish the FG-COMPASS’s concurrent validity by comparing its results to those of the TGMD-2. The study also sought further evidence of the FG-COMPASS’s inter-, intra-, and expert-rater reliability.</p>
<section id="concurrent-validity-between-the-fg-compass-and-the-tgmd-2" class="level2">
<h2 data-anchor-id="concurrent-validity-between-the-fg-compass-and-the-tgmd-2">Concurrent Validity Between the FG-COMPASS and the TGMD-2</h2>
<p>The concurrent validity assessment between the FG-COMPASS and the TGMD-2 provides insights into the agreement and potential discrepancies between the two tests. Establishing concurrent validity is important when testing motor skills because it shows how much a new instrument, like the FG-COMPASS, can be used in place of or with an established test, like the TGMD-2.</p>
<p>For the LFMS, the observed ICC of 0.68 falls within the ‘good’ range of agreement. This suggests that while both tests are aligned in their assessment of locomotor skills to a considerable extent, there are nuances or specific elements captured differently by each test. The Bland-Altman analysis further elucidates this observation. With a mean bias close to zero, there is virtually no systematic difference between the two tests regarding the locomotor subtest. The 95% limits of agreement, however, ranging from −1.95 to 1.95, show that individual scores can differ by almost 2 units (z-scores) in either direction. This range of disagreement suggests that, while the tests are generally aligned, they might occasionally produce different scores for the same individual.</p>
<p>The MFMS demonstrated a stronger alignment between the FG-COMPASS and TGMD-2, with an ICC of 0.89. This level of agreement underscores that both tests have a similar evaluation framework for manipulative skills. The Bland-Altman analysis further supports this, with a mean bias close to zero, indicating negligible systematic differences. The 95% limits of agreement, spanning from −1.25 to 1.25, are tighter than those of the locomotor subtest, indicating more consistent agreement between the tests for individual scores in this category. It should be noted that the FG-COMPASS has three locomotor and five manipulative skills compared to the TGMD-2, which has six skills in each subtest. This imbalance in the number of skills in the locomotor subtest between the two tests likely affected the observed difference. This can be verified in future studies since two new locomotor skills have recently been added <span class="citation" data-cites="perez2018">(<a href="#ref-perez2018" role="doc-biblioref">Perez, 2018</a>)</span> to the locomotor subtest of the FG-COMPASS.</p>
<p>For the TFMS, the ICC was also 0.89, mirroring the ‘excellent’ agreement observed in the manipulative subtest. The Bland-Altman analysis revealed a bias close to zero, again suggesting no meaningful systematic difference. The 95% limits of agreement ranged from −1.24 to 1.24, comparable to the manipulative subtest, showing a consistent level of individual score agreement across the entirety of the tests.</p>
<p>In light of these findings, the FG-COMPASS has acceptable concurrent validity with the TGMD-2, especially for assessing manipulative skills. Although there is ‘good’ agreement in the locomotor subtest, the results indicate that the FG-COMPASS can be reliably used in contexts where the TGMD-2 is the standard. However, practitioners should exercise caution and consider potential discrepancies, especially when assessing locomotor skills. The observed differences could be attributed to the inherent variations in test structures, scoring criteria, or specific motor skills targeted. Further investigation could explore these nuances to improve the FG-COMPASS or offer more specific direction on its use in conjunction with or instead of the TGMD-2.</p>
</section>
<section id="inter-rater-analysis" class="level2">
<h2 data-anchor-id="inter-rater-analysis">Inter-Rater Analysis</h2>
<p>The FG-COMPASS’s inter-rater reliability assessment provided insights into the agreement of different raters’ ratings. The weighted kappa values showed ‘good’ agreement for the LFMS, ‘excellent’ for the MFMS subtests, and ‘good’ for the overall test (TFMS). The agreement for the manipulative skills (0.77) was slightly higher when compared to the locomotor skills (0.66) - see Table&nbsp;2. This trend has been seen in previous research when measuring inter-rater reliability <span class="citation" data-cites="houwen2010 valentini2012">(<a href="#ref-houwen2010" role="doc-biblioref">Houwen et al., 2010</a>; <a href="#ref-valentini2012" role="doc-biblioref">Valentini, 2012</a>)</span>. In addition, a previous study <span class="citation" data-cites="furtado2018">(<a href="#ref-furtado2018" role="doc-biblioref">Furtado &amp; Gallagher, 2018</a>)</span> found similar but higher kappa scores for LFMS (0.89), MFMS (0.88), and TFMS (0.89) when investigating the inter-rater reliability of the FG-COMPASS. These scores suggest an ‘excellent’ agreement. In the <span class="citation" data-cites="furtado2018">Furtado and Gallagher (<a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span> study, raters assessed performers based on videos, whereas in the present study, we assessed live performances.</p>
<p>For the LFMS subtest, ‘Skip’ achieved the highest mean reliability (0.74), followed by ‘Jump’ (0.73), suggesting a ‘good’ agreement among raters for both skills. This is consistent with <span class="citation" data-cites="furtado2018">Furtado and Gallagher (<a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span> study, in which the inter-rater reliability for ‘Jump’ was found to be 0.92. On the other hand, ‘Hop’ had a lower mean reliability of 0.50, implying more variability in raters’ scores. More training on the performance criteria for ‘Hop’ was necessary to avoid guessing when classifying the performers. A potential misunderstanding of the criteria may also have led to guessing and poor agreement among the raters. Thirdly, borderline performances may have led to disagreement among raters. Performances from individuals who are transitioning between levels are difficult to classify. After closely examining the recorded performances, it was noted that approximately two-thirds of the performers could be considered “borderline.”</p>
<p>Within the MFMS subtest, ‘Dribble’ and ‘Catch’ had particularly high agreement scores of 0.89 and 0.86, respectively. These values are similar to <span class="citation" data-cites="furtado2018">Furtado and Gallagher (<a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span> study and reinforce the robustness of the scoring system for these skills. In contrast, the ‘Throw’ skill had an interesting result. While the kappa value (0.62) was considered ‘good’, it had a significantly higher standard deviation (0.22) than the other skills. The asterisks in the Table&nbsp;2 further highlight substantial disagreements between rater #5 and the other raters for this skill, suggesting potential inconsistencies or misinterpretations in the rating criteria or procedure for ‘Throw’. In the current study, the weighted kappa of 0.62 (good) would increase to 0.79 (excellent) if rater #5 was removed from the analysis. Rater #5 showed the largest disagreement compared to the other four raters (see Table&nbsp;2). The estimated agreement values were 0.45, 0.35, 0.31, and 0.40 between rater #5 and raters 1, 2, 3, and 4, respectively. These values are considerably lower when compared to the pair agreement values for the other raters, which ranged from 0.71 to 0.85. Such a discrepancy suggests that rater #5 misunderstood the criteria associated with ‘Throw’. The kappa values for ‘Kick’ (0.68) and ‘Strike’ (0.78) are slightly lower when compared to the <span class="citation" data-cites="furtado2018">Furtado and Gallagher (<a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span> study (e.g., Kick = 0.90, Strike = 0.86). The reason for the difference can be traced back to the fact that the raters in the current study evaluated performances in a live setting. In contrast, the raters in the 2018 study evaluated performances recorded on video.</p>
<p>The TFMS combined score reliability of 0.72 reflects a balanced representation of the LFMS and MFMS subtests, adding to the tool’s reliability. However, it is important to address the discrepancies and variations among the raters, especially the pronounced differences with rater #5 for the skill of ‘Throw’. Such discrepancies could arise from several factors, including differing interpretations of scoring criteria, rater training, or even the subjective nature of certain skills. Future attempts to collect inter-rater reliability for the FG-COMPASS should give special attention to standardizing interpretations and emphasizing areas where disagreements are most apparent.</p>
</section>
<section id="intra-rater-reliability" class="level2">
<h2 data-anchor-id="intra-rater-reliability">Intra-Rater Reliability</h2>
<p>Evaluating intra-rater reliability is crucial for assessing the consistency of measurements taken by raters at two different times, typically one week apart. Because the FG-COMPASS is being developed to assess motor skill performance in a live setting, this study was particularly focused on how live assessments compare with video recordings of the same performance. Following the live assessment of performances, which were recorded on video, participants returned to the lab twice to re-assess the recorded performances: one week after the live performances and again two weeks after the live performances. The mean values presented in Table&nbsp;4 provide a comprehensive overview of each rater’s consistency across the three combinations: live versus recording - time 1 (IR1), live versus recording - time 2 (IR2), and recording time 1 versus recording time 2 (IR3). Based on Table&nbsp;4, the average reliability score for the IR1 comparison is a noteworthy finding. This evaluation is especially interesting because it assesses the agreement between real-time ratings and those gathered from video recordings one week after the initial assessments.</p>
<p>The results indicate a ‘good’ agreement for LFMS (0.69), MFMS (0.70), and TFMS (0.70). Regarding individual skills, ‘Skip’ demonstrated a high mean kappa intra-rater reliability of 0.80 for IR1. This suggests an ‘excellent’ agreement between the live and the first video assessments for this skill. On the other hand, the skill ‘Jump’ had a lower mean reliability score of 0.60, suggesting a possible inconsistency in intra-rater reliability. The TFMS mean kappa value (0.70) observed between live ratings and video recordings is considered ‘good’. This value is lower than that obtained (0.91) in a previous study <span class="citation" data-cites="furtado2018">(<a href="#ref-furtado2018" role="doc-biblioref">Furtado &amp; Gallagher, 2018</a>)</span>, which assessed intra-rater reliability from video recordings. This difference was expected since assessing performance from videos is less challenging compared to live assessment.</p>
</section>
<section id="raters-vs.-expert-agreement-for-the-fg-compass" class="level2">
<h2 data-anchor-id="raters-vs.-expert-agreement-for-the-fg-compass">Raters vs.&nbsp;Expert Agreement for the FG-COMPASS</h2>
<p>The expert-rater agreement is the degree to which raters in this study agreed with an expert familiar with the FG-COMPASS testing protocol. Thus, one of the aims of this study was to measure the level of agreement between the ratings of five raters and the expert’s video scores.</p>
<p>An average kappa value of 0.64 indicates that the agreement between the raters and the expert in the LFMS category was generally ‘good’. For ‘Hop’, the raters’ evaluations closely aligned with the expert, yielding a mean kappa value of 0.67. The ‘Jump’ skill exhibited even greater alignment between the raters and the expert, with a kappa value of 0.73. On the other hand, the ‘Skip’ skill demonstrated a fair agreement level, with an average kappa value of 0.53. The ‘Hop’ and ‘Jump’ results indicate a shared interpretation of the evaluation criteria between the raters and the expert. The variability in kappa values for ‘Skip’ indicates potential differences in interpretation or understanding between the raters and the expert, which may need further clarification or training for the raters.</p>
<p>When investigating agreement between trained raters and an expert from video performances, <span class="citation" data-cites="furtado2012">Furtado and Gallagher (<a href="#ref-furtado2012" role="doc-biblioref">2012</a>)</span> found ‘excellent’ and ‘good’ agreement between raters and an expert for ‘Skip’ (0.77) and ‘Jump’ (0.70), respectively, and ‘excellent’ agreement for ‘Hop’ (0.85). It is important to note that the decision tree for “Jump’ was modified following the <span class="citation" data-cites="furtado2012">Furtado and Gallagher (<a href="#ref-furtado2012" role="doc-biblioref">2012</a>)</span> study and re-assessed recently <span class="citation" data-cites="furtado2018">(<a href="#ref-furtado2018" role="doc-biblioref">Furtado &amp; Gallagher, 2018</a>)</span>. The agreement improved from 0.70 (good) to 0.88 (excellent). The lower kappa score (0.73) observed in the current study for ‘Jump’ is likely due to rater variability and the source of observation, which in the current study was from live performance compared to video performance in the 2018 study.</p>
<p>A mean kappa value of 0.74 indicated an ‘excellent’ alignment between the raters and the expert in the MFMS category. The evaluations for the ‘Throw’ and ‘Kick’ skills aligned well with the expert’s ratings, resulting in ‘excellent’ (0.75) and ‘good’ (0.73) agreement levels, respectively. The scores for ‘Dribble’ and ‘Catch’ had higher scores, with mean kappa values of 0.86 and 0.83, respectively. Like ‘Jump’, the decision trees for ‘Dribble’ and ‘Catch’ were modified following the <span class="citation" data-cites="furtado2012">Furtado and Gallagher (<a href="#ref-furtado2012" role="doc-biblioref">2012</a>)</span> study and re-assessed in the <span class="citation" data-cites="furtado2018">Furtado and Gallagher (<a href="#ref-furtado2018" role="doc-biblioref">2018</a>)</span> study. The kappa values improved from 0.72 (good) to 0.81 (excellent) and 0.72 (good) to 0.94 (excellent) for ‘Dribble’ and ‘Catch’, respectively. For the current study, ‘Strike’ displayed fair agreement (0.51). In its initial assessment <span class="citation" data-cites="furtado2012">(<a href="#ref-furtado2012" role="doc-biblioref">Furtado &amp; Gallagher, 2012</a>)</span>, the kappa value for ‘Strike’ was 0.79. This value, however, significantly improved to 0.93 in a subsequent study <span class="citation" data-cites="furtado2018">(<a href="#ref-furtado2018" role="doc-biblioref">Furtado &amp; Gallagher, 2018</a>)</span>. Similar to ‘Skip’, the differences in the kappa values for ‘Strike’ suggest that there may be discrepancies in how the raters and the expert interpret or understand the test’s protocol or criteria, which may require additional clarification or training for the raters in future studies.</p>
<p>When looking at all eight FG-COMPASS skills, an average kappa value of 0.70 for the total test (TFMS) suggests a good agreement between the expert and the raters. The empirical findings highlight the significance of familiarizing oneself with the test protocol before utilizing the FG-COMPASS, particularly in skills where agreement with the expert was moderate (e.g., skip and strike).</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>This study looked closely at the FG-COMPASS. It focused on how well it worked with the TGMD-2, how reliable it was between and within raters, and how much an expert and raters agreed. The results demonstrate promising evidence of the FG-COMPASS’s applicability and robustness as a motor skill assessment tool. The assessment of concurrent validity with the TGMD-2 shows an excellent match between the two instruments. This shows that the FG-COMPASS could be a good alternative or supplementary tool. The ‘good’ agreement in the locomotor subtest calls for attention to specific nuances, which may be further explored in future studies. The evaluation of inter-rater reliability reveals ‘good’ agreement for LFMS, ‘excellent’ for MFMS, and ‘good’ for the overall test (TFMS). The discrepancies observed, especially with rater #5 for ‘Throw’, underline the importance of standardized interpretations and training among raters. The intra-rater reliability assessment, which explored consistency in live versus video assessments, indicates ‘good’ agreement. The variance in some skills, such as ‘Jump’, highlights the complexities of live assessment and warrants further examination. Finally, the analysis of agreement between raters and an expert emphasizes the significance of understanding and aligning with the test protocol. The agreement for LFMS was deemed ‘good’, while MFMS received an ‘excellent’ rating, resulting in an overall ‘good’ agreement. This reinforces the FG-COMPASS’s ability to provide a strong agreement between FMS classifications from raters and a ‘gold standard’.</p>
<section id="implications-and-future-directions" class="level2">
<h2 data-anchor-id="implications-and-future-directions">Implications and Future Directions</h2>
<p>The findings collectively support the FG-COMPASS as a valuable instrument for motor skill assessment. The observed discrepancies in some areas provide constructive insights for refining the test, ensuring better alignment with established tests like the TGMD-2, and enhancing rater training and standardization. Future research should delve into the subtle differences in the locomotor subtest and seek to understand the variations in rater interpretations. Enhancing the FG-COMPASS through ongoing refinement and validation is an important step toward more accurate and consistent motor skill evaluations in research and practical settings. This study contributes to the growing body of knowledge supporting FG-COMPASS’s efficacy. It sets the stage for its broader implementation and potential impact on motor skill assessment.</p>
</section>
</section>
<section id="limitations" class="level1">
<h1>Limitations</h1>
<p>Although precautions were taken, it’s important to note that this study has some limitations. Compared to the TGMD-2, which consists of six locomotor and six manipulative skills, the FG-COMPASS has three locomotor and five manipulative skills. This discrepancy may have affected the alignment between the two tests, particularly in the locomotor subtest. Second, the discrepancies observed with certain raters, such as rater #5, may point to inconsistencies in rater training or interpretation of the criteria. This could affect the overall reliability of the ratings. Third, the variability in kappa values between raters and the expert for certain skills indicates potential differences in interpretation or understanding of the evaluation criteria. This may warrant further clarification or training. And fourth, due to the small sample size, there may be limitations in generalizing the findings to broader populations.</p>
<section id="declaration-of-conflicting-interest" class="level2">
<h2 data-anchor-id="declaration-of-conflicting-interest">Declaration of Conflicting Interest</h2>
<p>The authors state that they have no conflicts of interest.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="references" class="level1">
<h1>References</h1>
<!-- References will auto-populate in the refs div below -->
<div id="refs" class="references csl-bib-body hanging-indent" data-line-spacing="2" role="list">
<div id="ref-adams1999" class="csl-entry" role="listitem">
Adams, R. (1999). Revised <span>Physical Activity Readiness Questionnaire</span>. <em>Canadian Family Physician</em>, <em>45</em>, 992–1005. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2328306/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2328306/</a>
</div>
<div id="ref-barnett2009" class="csl-entry" role="listitem">
Barnett, L. M., van Beurden, E., Morgan, P. J., Brooks, L. O., &amp; Beard, J. R. (2009). Childhood motor skill proficiency as a predictor of adolescent physical activity. <em>The Journal of Adolescent Health: Official Publication of the Society for Adolescent Medicine</em>, <em>44</em>(3), 252–259. <a href="https://doi.org/10.1016/j.jadohealth.2008.07.004">https://doi.org/10.1016/j.jadohealth.2008.07.004</a>
</div>
<div id="ref-bayer2009" class="csl-entry" role="listitem">
Bayer, O., Bolte, G., Morlock, G., Rückinger, S., von Kries, R., &amp; GME-Study Group. (2009). A simple assessment of physical activity is associated with obesity and motor fitness in pre-school children. <em>Public Health Nutrition</em>, <em>12</em>(8), 1242–1247. <a href="https://doi.org/10.1017/S1368980008003753">https://doi.org/10.1017/S1368980008003753</a>
</div>
<div id="ref-bellows2013" class="csl-entry" role="listitem">
Bellows, L. L., Davies, P. L., Anderson, J., &amp; Kennedy, C. (2013). Effectiveness of a physical activity intervention for head start preschoolers: A randomized intervention study. <em>AJOT: American Journal of Occupational Therapy</em>, <em>67</em>(1), 28+. <a href="http://go.galegroup.com/ps/i.do?id=GALE%7CA314443342&amp;v=2.1&amp;u=csunorthridge&amp;it=r&amp;p=HRCA&amp;sw=w&amp;asid=9496686804b2cdbe2f7f6b6205138068">http://go.galegroup.com/ps/i.do?id=GALE%7CA314443342&amp;v=2.1&amp;u=csunorthridge&amp;it=r&amp;p=HRCA&amp;sw=w&amp;asid=9496686804b2cdbe2f7f6b6205138068</a>
</div>
<div id="ref-bland1986" class="csl-entry" role="listitem">
Bland, J. M., &amp; Altman, D. (1986). Statistical methods for assessing agreement between two methods of clinical measurement. <em>The Lancet</em>, <em>327</em>(8476), 307–310. <a href="https://doi.org/10.1016/S0140-6736(86)90837-8">https://doi.org/10.1016/S0140-6736(86)90837-8</a>
</div>
<div id="ref-castelli2007" class="csl-entry" role="listitem">
Castelli, D. M., &amp; Valley, J. A. (2007). Chapter 3: <span>The Relationship</span> of <span>Physical Fitness</span> and <span>Motor Competence</span> to <span>Physical Activity</span>. <em>Journal of Teaching in Physical Education</em>, <em>26</em>(4), 358–374. <a href="http://www.eric.ed.gov/ERICWebPortal/detail?accno=EJ776156">http://www.eric.ed.gov/ERICWebPortal/detail?accno=EJ776156</a>
</div>
<div id="ref-cicchetti1994" class="csl-entry" role="listitem">
Cicchetti, D. V. (1994). Guidelines, criteria, and rules of thumb for evaluating normed and standardized assessment instruments in psychology. <em>Psychological Assessment</em>, <em>6</em>(4), 284–290. <a href="https://doi.org/10.1037/1040-3590.6.4.284">https://doi.org/10.1037/1040-3590.6.4.284</a>
</div>
<div id="ref-cliff2012" class="csl-entry" role="listitem">
Cliff, D. P., Okely, A. D., Morgan, P. J., Jones, R. A., Steele, J. R., &amp; Baur, L. A. (2012). Proficiency deficiency: <span>Mastery</span> of fundamental movement skills and skill components in overweight and obese children. <em>Obesity</em>, <em>20</em>(5), 1024–1033. <a href="https://doi.org/10.1038/oby.2011.241">https://doi.org/10.1038/oby.2011.241</a>
</div>
<div id="ref-cools2009" class="csl-entry" role="listitem">
Cools, W., Martelaer, K. D., Samaey, C., &amp; Andries, C. (2009). Movement <span>Skill Assessment</span> of <span>Typically Developing Preschool Children</span>: <span>A Review</span> of <span>Seven Movement Skill Assessment Tools</span>. <em>Journal of Sports Science &amp; Medicine</em>, <em>8</em>(2), 154–168. <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3761481/">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3761481/</a>
</div>
<div id="ref-fisher2005" class="csl-entry" role="listitem">
Fisher, A., Reilly, J. J., Kelly, L. A., Montgomery, C., Williamson, A., Paton, J. Y., &amp; Grant, S. (2005). Fundamental <span>Movement Skills</span> and <span>Habitual Physical Activity</span> in <span>Young Children</span>. <em>Medicine &amp; Science in Sports &amp; Exercise</em>, <em>37</em>(4), 684–688.
</div>
<div id="ref-fleiss1973" class="csl-entry" role="listitem">
Fleiss, J. L., &amp; Cohen, J. (1973). The equivalence of weighted kappa and the intraclass correlation coefficient as measures of reliability. <em>Educational and Psychological Measurement</em>, <em>33</em>(3), 613–619. <a href="https://doi.org/10.1177/001316447303300309">https://doi.org/10.1177/001316447303300309</a>
</div>
<div id="ref-furtado2004" class="csl-entry" role="listitem">
Furtado, O., Jr. (2004). <em>Furtado-<span>Gallagher</span> movement skill assessment: Collecting evidence for content-related validity</em> [Master’s thesis, <span>University of Pittsburgh</span>]. <a href="http://etd.library.pitt.edu/ETD/available/etd-12042004-093510/">http://etd.library.pitt.edu/ETD/available/etd-12042004-093510/</a>
</div>
<div id="ref-furtado2012" class="csl-entry" role="listitem">
Furtado, O., Jr, &amp; Gallagher, J. D. (2012). The reliability of classification decisions for the <span>Furtado-Gallagher Computerized Observational Movement Pattern Assessment System</span> - <span>FG-COMPASS</span>. <em>Research Quarterly for Exercise and Sport</em>, <em>83</em>(3), 383–390. <a href="https://doi.org/10.1080/02701367.2012.10599872">https://doi.org/10.1080/02701367.2012.10599872</a>
</div>
<div id="ref-furtado2018" class="csl-entry" role="listitem">
Furtado, O., Jr, &amp; Gallagher, J. D. (2018). Expert-rater agreement and inter-/intrarater reliability for the <span>Furtado</span>–<span>Gallagher Computerized Observational Movement Pattern Assessment System</span>. <em>Perceptual and Motor Skills</em>, <em>125</em>(3), 423–437. <a href="https://doi.org/10.1177/0031512518769205">https://doi.org/10.1177/0031512518769205</a>
</div>
<div id="ref-gabbard2021" class="csl-entry" role="listitem">
Gabbard, C. (2021). <em>Lifelong <span>Motor Development</span></em>. <span>Lippincott Williams &amp; Wilkins</span>.
</div>
<div id="ref-giavarina2015" class="csl-entry" role="listitem">
Giavarina, D. (2015). Understanding <span>Bland Altman</span> analysis. <em>Biochemia Medica</em>, <em>25</em>(2), 141–151. <a href="https://doi.org/10.11613/BM.2015.015">https://doi.org/10.11613/BM.2015.015</a>
</div>
<div id="ref-graf2004" class="csl-entry" role="listitem">
Graf, C., Koch, B., Kretschmann-Kandel, E., Falkowski, G., Christ, H., Coburger, S., Lehmacher, W., Bjarnason-Wehrens, B., Platen, P., Tokarski, W., Predel, H. G., &amp; Dordel, S. (2004). Correlation <span>Between Bmi</span>, <span>Leisure Habits</span> and <span>Motor Abilities</span> in <span>Childhood</span> (chilt-<span>Project</span>). <em>International Journal of Obesity</em>, <em>28</em>(1), 22–26. <a href="https://doi.org/10.1038/sj.ijo.0802428">https://doi.org/10.1038/sj.ijo.0802428</a>
</div>
<div id="ref-houwen2010" class="csl-entry" role="listitem">
Houwen, S., Hartman, E., Jonker, L., &amp; Visscher, C. (2010). Reliability and validity of the <span>TGMD-2</span> in primary-school-age children with visual impairments. <em>Adapted Physical Activity Quarterly</em>, <em>27</em>(2), 143–159. <a href="http://journals.humankinetics.com/AcuCustom/Sitename/Documents/DocumentItem/17945.pdf">http://journals.humankinetics.com/AcuCustom/Sitename/Documents/DocumentItem/17945.pdf</a>
</div>
<div id="ref-lemos2012" class="csl-entry" role="listitem">
Lemos, A. G. (2012). Physical <span>Education</span> in <span>Kindergarten Promotes Fundamental Motor Skill Development</span>. <em>Advances in Physical Education</em>, <em>02</em>(01), 17–21. <a href="https://doi.org/10.4236/ape.2012.21003">https://doi.org/10.4236/ape.2012.21003</a>
</div>
<div id="ref-light1971" class="csl-entry" role="listitem">
Light, R. J. (1971). Measures of response agreement for qualitative data: <span>Some</span> generalizations and alternatives. <em>Psychological Bulletin</em>, <em>76</em>(5), 365–377. <a href="https://doi.org/10.1037/h0031643">https://doi.org/10.1037/h0031643</a>
</div>
<div id="ref-lopes2012" class="csl-entry" role="listitem">
Lopes, V. P., Stodden, D. F., Bianchi, M. M., Maia, J. A. R., &amp; Rodrigues, L. P. (2012). Correlation between <span>BMI</span> and motor coordination in children. <em>Journal of Science and Medicine in Sport</em>, <em>15</em>(1), 38–43. <a href="https://doi.org/10.1016/j.jsams.2011.07.005">https://doi.org/10.1016/j.jsams.2011.07.005</a>
</div>
<div id="ref-mcgraw1996" class="csl-entry" role="listitem">
McGraw, K. O., &amp; Wong, S. P. (1996). Forming inferences about some intraclass correlation coefficients. <em>Psychological Methods</em>, <em>1</em>(1), 30–46. <a href="https://doi.org/10.1037/1082-989X.1.1.30">https://doi.org/10.1037/1082-989X.1.1.30</a>
</div>
<div id="ref-mckenzie2002" class="csl-entry" role="listitem">
McKenzie, T. L., Sallis, J. F., Broyles, S. L., Zive, M. M., Nader, P. R., Berry, C. C., &amp; Brennan, J. J. (2002). Childhood <span>Movement Skills</span>: <span>Predictors</span> of <span>Physical Activity</span> in <span>Anglo American</span> and <span>Mexican American Adolescents</span>. <em>Research Quarterly for Exercise and Sport</em>, <em>73</em>(3), 238–244. <a href="https://doi.org/10.1080/02701367.2002.10609017">https://doi.org/10.1080/02701367.2002.10609017</a>
</div>
<div id="ref-perez2018" class="csl-entry" role="listitem">
Perez, L. (2018). <em>Investigating expert-rater agreement and inter/intra-rater reliability of two fundamental movement skills for the locomotor subscale of the fg-compass</em> [Thesis, <span>California State University, Northridge</span>]. <a href="http://dspace.calstate.edu/handle/10211.3/199459">http://dspace.calstate.edu/handle/10211.3/199459</a>
</div>
<div id="ref-provost2000" class="csl-entry" role="listitem">
Provost, B., Crowe, T. K., &amp; McClain, C. (2000). Concurrent validity of the <span>Bayley Scales</span> of <span>Infant Development II Motor Scale</span> and the <span>Peabody Developmental Motor Scales</span> in two-year-old children. <em>Physical &amp; Occupational Therapy in Pediatrics</em>, <em>20</em>(1), 5–18. <a href="http://www.ncbi.nlm.nih.gov/pubmed/11293915">http://www.ncbi.nlm.nih.gov/pubmed/11293915</a>
</div>
<div id="ref-jamovi233" class="csl-entry" role="listitem">
The jamovi project. (2022). <em>Jamovi</em> (Version 2.3.3). <a href="https://www.jamovi.org">https://www.jamovi.org</a>
</div>
<div id="ref-ulrich2000" class="csl-entry" role="listitem">
Ulrich, D. (2000). <em>Test of gross motor development: <span>Examiner</span>’s manual</em>. <span>Pro-Ed</span>.
</div>
<div id="ref-valentini2012" class="csl-entry" role="listitem">
Valentini, N. C. (2012). Validity and <span>Reliability</span> of the <span>TGMD-2</span> for <span>Brazilian Children</span>. <em>Journal of Motor Behavior</em>, <em>44</em>(4), 275–280. <a href="https://doi.org/10.1080/00222895.2012.700967">https://doi.org/10.1080/00222895.2012.700967</a>
</div>
<div id="ref-valentini2004" class="csl-entry" role="listitem">
Valentini, N. C., &amp; Rudisill, M. E. (2004). An <span>Inclusive Mastery Climate Intervention</span> and the <span>Motor Skill Development</span> of <span>Children</span> with and <span>Without Disabilities</span>. <em>Adapted Physical Activity Quarterly</em>, <em>21</em>(4), 330–347. <a href="https://doi.org/10.1123/apaq.21.4.330">https://doi.org/10.1123/apaq.21.4.330</a>
</div>
<div id="ref-wiart2001" class="csl-entry" role="listitem">
Wiart, L., &amp; Darrah, J. (2001). Review of four tests of gross motor development. <em>Developmental Medicine and Child Neurology</em>, <em>43</em>(4), 279–285. <a href="https://doi.org/10.1017/s0012162201000536">https://doi.org/10.1017/s0012162201000536</a>
</div>
<div id="ref-woods2007" class="csl-entry" role="listitem">
Woods, A. M., Bolton, K. N., Graber, K. C., &amp; Crull, G. S. (2007). Chapter 5: <span>Influences</span> of <span>Perceived Motor Competence</span> and <span>Motives</span> on <span>Children</span>’s <span>Physical Activity</span>. <em>Journal of Teaching in Physical Education</em>, <em>26</em>(4), 390–403. <a href="https://doi.org/10.1123/jtpe.26.4.390">https://doi.org/10.1123/jtpe.26.4.390</a>
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>